// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/bridge.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<AppEventDto> dco_decode_StreamSink_app_event_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogLineDto> dco_decode_StreamSink_log_line_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<RetryProgressDto> dco_decode_StreamSink_retry_progress_dto_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SessionFollowUpdateDto>
  dco_decode_StreamSink_session_follow_update_dto_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountPollDto dco_decode_account_poll_dto(dynamic raw);

  @protected
  AccountServiceDto dco_decode_account_service_dto(dynamic raw);

  @protected
  AccountUserDto dco_decode_account_user_dto(dynamic raw);

  @protected
  AcpAgentDto dco_decode_acp_agent_dto(dynamic raw);

  @protected
  AcpAgentFlagDto dco_decode_acp_agent_flag_dto(dynamic raw);

  @protected
  AcpAgentsDto dco_decode_acp_agents_dto(dynamic raw);

  @protected
  AcpAuthDto dco_decode_acp_auth_dto(dynamic raw);

  @protected
  AcpAuthMethodDto dco_decode_acp_auth_method_dto(dynamic raw);

  @protected
  AcpBinaryOverrideDto dco_decode_acp_binary_override_dto(dynamic raw);

  @protected
  AcpCommandDto dco_decode_acp_command_dto(dynamic raw);

  @protected
  AcpConfigOptionDto dco_decode_acp_config_option_dto(dynamic raw);

  @protected
  AcpConfigValueDto dco_decode_acp_config_value_dto(dynamic raw);

  @protected
  AcpCustomAgentDto dco_decode_acp_custom_agent_dto(dynamic raw);

  @protected
  AcpDataModeDto dco_decode_acp_data_mode_dto(dynamic raw);

  @protected
  AcpEnvVarDto dco_decode_acp_env_var_dto(dynamic raw);

  @protected
  AcpGatewayDto dco_decode_acp_gateway_dto(dynamic raw);

  @protected
  AcpJobDto dco_decode_acp_job_dto(dynamic raw);

  @protected
  AcpSaveDto dco_decode_acp_save_dto(dynamic raw);

  @protected
  AcpServeDto dco_decode_acp_serve_dto(dynamic raw);

  @protected
  AcpSettingsDto dco_decode_acp_settings_dto(dynamic raw);

  @protected
  AppCapabilitiesDto dco_decode_app_capabilities_dto(dynamic raw);

  @protected
  AppEventDto dco_decode_app_event_dto(dynamic raw);

  @protected
  AppServeDto dco_decode_app_serve_dto(dynamic raw);

  @protected
  AppServeStatusDto dco_decode_app_serve_status_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AccountUserDto dco_decode_box_autoadd_account_user_dto(dynamic raw);

  @protected
  AcpAuthDto dco_decode_box_autoadd_acp_auth_dto(dynamic raw);

  @protected
  AcpCustomAgentDto dco_decode_box_autoadd_acp_custom_agent_dto(dynamic raw);

  @protected
  AcpJobDto dco_decode_box_autoadd_acp_job_dto(dynamic raw);

  @protected
  AcpSettingsDto dco_decode_box_autoadd_acp_settings_dto(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ThreadConfigDto dco_decode_box_autoadd_thread_config_dto(dynamic raw);

  @protected
  ThreadHistoryDto dco_decode_box_autoadd_thread_history_dto(dynamic raw);

  @protected
  ThreadRuntimeConfigDto dco_decode_box_autoadd_thread_runtime_config_dto(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CodexAuthStatusDto dco_decode_codex_auth_status_dto(dynamic raw);

  @protected
  CodexLoginStartDto dco_decode_codex_login_start_dto(dynamic raw);

  @protected
  CodexSetupStatusDto dco_decode_codex_setup_status_dto(dynamic raw);

  @protected
  ConfigView dco_decode_config_view(dynamic raw);

  @protected
  DeviceCodeDto dco_decode_device_code_dto(dynamic raw);

  @protected
  DirEntryDto dco_decode_dir_entry_dto(dynamic raw);

  @protected
  FileEntryDto dco_decode_file_entry_dto(dynamic raw);

  @protected
  FilePreviewDto dco_decode_file_preview_dto(dynamic raw);

  @protected
  ForceResumeReportDto dco_decode_force_resume_report_dto(dynamic raw);

  @protected
  HistoryCacheStatusDto dco_decode_history_cache_status_dto(dynamic raw);

  @protected
  HolderDto dco_decode_holder_dto(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AccountServiceDto> dco_decode_list_account_service_dto(dynamic raw);

  @protected
  List<AcpAgentDto> dco_decode_list_acp_agent_dto(dynamic raw);

  @protected
  List<AcpAgentFlagDto> dco_decode_list_acp_agent_flag_dto(dynamic raw);

  @protected
  List<AcpAuthMethodDto> dco_decode_list_acp_auth_method_dto(dynamic raw);

  @protected
  List<AcpBinaryOverrideDto> dco_decode_list_acp_binary_override_dto(
    dynamic raw,
  );

  @protected
  List<AcpCommandDto> dco_decode_list_acp_command_dto(dynamic raw);

  @protected
  List<AcpConfigOptionDto> dco_decode_list_acp_config_option_dto(dynamic raw);

  @protected
  List<AcpConfigValueDto> dco_decode_list_acp_config_value_dto(dynamic raw);

  @protected
  List<AcpCustomAgentDto> dco_decode_list_acp_custom_agent_dto(dynamic raw);

  @protected
  List<AcpDataModeDto> dco_decode_list_acp_data_mode_dto(dynamic raw);

  @protected
  List<AcpEnvVarDto> dco_decode_list_acp_env_var_dto(dynamic raw);

  @protected
  List<AcpGatewayDto> dco_decode_list_acp_gateway_dto(dynamic raw);

  @protected
  List<AppServeStatusDto> dco_decode_list_app_serve_status_dto(dynamic raw);

  @protected
  List<DirEntryDto> dco_decode_list_dir_entry_dto(dynamic raw);

  @protected
  List<FileEntryDto> dco_decode_list_file_entry_dto(dynamic raw);

  @protected
  List<HolderDto> dco_decode_list_holder_dto(dynamic raw);

  @protected
  List<LocalSessionDto> dco_decode_list_local_session_dto(dynamic raw);

  @protected
  List<ModelInfoDto> dco_decode_list_model_info_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ServiceIdDto> dco_decode_list_service_id_dto(dynamic raw);

  @protected
  List<SubStatusDto> dco_decode_list_sub_status_dto(dynamic raw);

  @protected
  List<ThreadItemDto> dco_decode_list_thread_item_dto(dynamic raw);

  @protected
  List<ThreadMetaDto> dco_decode_list_thread_meta_dto(dynamic raw);

  @protected
  List<TurnItemsPageDto> dco_decode_list_turn_items_page_dto(dynamic raw);

  @protected
  List<TurnSummaryDto> dco_decode_list_turn_summary_dto(dynamic raw);

  @protected
  LocalSessionDto dco_decode_local_session_dto(dynamic raw);

  @protected
  LogLineDto dco_decode_log_line_dto(dynamic raw);

  @protected
  ModelInfoDto dco_decode_model_info_dto(dynamic raw);

  @protected
  OlderPageDto dco_decode_older_page_dto(dynamic raw);

  @protected
  OpenCodeServeDto dco_decode_open_code_serve_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AccountUserDto? dco_decode_opt_box_autoadd_account_user_dto(dynamic raw);

  @protected
  AcpAuthDto? dco_decode_opt_box_autoadd_acp_auth_dto(dynamic raw);

  @protected
  AcpJobDto? dco_decode_opt_box_autoadd_acp_job_dto(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ThreadHistoryDto? dco_decode_opt_box_autoadd_thread_history_dto(dynamic raw);

  @protected
  ThreadRuntimeConfigDto? dco_decode_opt_box_autoadd_thread_runtime_config_dto(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  ProjectConfigDto dco_decode_project_config_dto(dynamic raw);

  @protected
  RetryProgressDto dco_decode_retry_progress_dto(dynamic raw);

  @protected
  ServiceIdDto dco_decode_service_id_dto(dynamic raw);

  @protected
  SessionFollowUpdateDto dco_decode_session_follow_update_dto(dynamic raw);

  @protected
  SessionLivenessDto dco_decode_session_liveness_dto(dynamic raw);

  @protected
  SubStatusDto dco_decode_sub_status_dto(dynamic raw);

  @protected
  ThreadConfigDto dco_decode_thread_config_dto(dynamic raw);

  @protected
  ThreadHistoryDto dco_decode_thread_history_dto(dynamic raw);

  @protected
  ThreadItemDto dco_decode_thread_item_dto(dynamic raw);

  @protected
  ThreadMetaDto dco_decode_thread_meta_dto(dynamic raw);

  @protected
  ThreadRuntimeConfigDto dco_decode_thread_runtime_config_dto(dynamic raw);

  @protected
  TurnItemsPageDto dco_decode_turn_items_page_dto(dynamic raw);

  @protected
  TurnSummaryDto dco_decode_turn_summary_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WebLoginStartDto dco_decode_web_login_start_dto(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<AppEventDto> sse_decode_StreamSink_app_event_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogLineDto> sse_decode_StreamSink_log_line_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<RetryProgressDto> sse_decode_StreamSink_retry_progress_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SessionFollowUpdateDto>
  sse_decode_StreamSink_session_follow_update_dto_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountPollDto sse_decode_account_poll_dto(SseDeserializer deserializer);

  @protected
  AccountServiceDto sse_decode_account_service_dto(
    SseDeserializer deserializer,
  );

  @protected
  AccountUserDto sse_decode_account_user_dto(SseDeserializer deserializer);

  @protected
  AcpAgentDto sse_decode_acp_agent_dto(SseDeserializer deserializer);

  @protected
  AcpAgentFlagDto sse_decode_acp_agent_flag_dto(SseDeserializer deserializer);

  @protected
  AcpAgentsDto sse_decode_acp_agents_dto(SseDeserializer deserializer);

  @protected
  AcpAuthDto sse_decode_acp_auth_dto(SseDeserializer deserializer);

  @protected
  AcpAuthMethodDto sse_decode_acp_auth_method_dto(SseDeserializer deserializer);

  @protected
  AcpBinaryOverrideDto sse_decode_acp_binary_override_dto(
    SseDeserializer deserializer,
  );

  @protected
  AcpCommandDto sse_decode_acp_command_dto(SseDeserializer deserializer);

  @protected
  AcpConfigOptionDto sse_decode_acp_config_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  AcpConfigValueDto sse_decode_acp_config_value_dto(
    SseDeserializer deserializer,
  );

  @protected
  AcpCustomAgentDto sse_decode_acp_custom_agent_dto(
    SseDeserializer deserializer,
  );

  @protected
  AcpDataModeDto sse_decode_acp_data_mode_dto(SseDeserializer deserializer);

  @protected
  AcpEnvVarDto sse_decode_acp_env_var_dto(SseDeserializer deserializer);

  @protected
  AcpGatewayDto sse_decode_acp_gateway_dto(SseDeserializer deserializer);

  @protected
  AcpJobDto sse_decode_acp_job_dto(SseDeserializer deserializer);

  @protected
  AcpSaveDto sse_decode_acp_save_dto(SseDeserializer deserializer);

  @protected
  AcpServeDto sse_decode_acp_serve_dto(SseDeserializer deserializer);

  @protected
  AcpSettingsDto sse_decode_acp_settings_dto(SseDeserializer deserializer);

  @protected
  AppCapabilitiesDto sse_decode_app_capabilities_dto(
    SseDeserializer deserializer,
  );

  @protected
  AppEventDto sse_decode_app_event_dto(SseDeserializer deserializer);

  @protected
  AppServeDto sse_decode_app_serve_dto(SseDeserializer deserializer);

  @protected
  AppServeStatusDto sse_decode_app_serve_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AccountUserDto sse_decode_box_autoadd_account_user_dto(
    SseDeserializer deserializer,
  );

  @protected
  AcpAuthDto sse_decode_box_autoadd_acp_auth_dto(SseDeserializer deserializer);

  @protected
  AcpCustomAgentDto sse_decode_box_autoadd_acp_custom_agent_dto(
    SseDeserializer deserializer,
  );

  @protected
  AcpJobDto sse_decode_box_autoadd_acp_job_dto(SseDeserializer deserializer);

  @protected
  AcpSettingsDto sse_decode_box_autoadd_acp_settings_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ThreadConfigDto sse_decode_box_autoadd_thread_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  ThreadHistoryDto sse_decode_box_autoadd_thread_history_dto(
    SseDeserializer deserializer,
  );

  @protected
  ThreadRuntimeConfigDto sse_decode_box_autoadd_thread_runtime_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CodexAuthStatusDto sse_decode_codex_auth_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  CodexLoginStartDto sse_decode_codex_login_start_dto(
    SseDeserializer deserializer,
  );

  @protected
  CodexSetupStatusDto sse_decode_codex_setup_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  ConfigView sse_decode_config_view(SseDeserializer deserializer);

  @protected
  DeviceCodeDto sse_decode_device_code_dto(SseDeserializer deserializer);

  @protected
  DirEntryDto sse_decode_dir_entry_dto(SseDeserializer deserializer);

  @protected
  FileEntryDto sse_decode_file_entry_dto(SseDeserializer deserializer);

  @protected
  FilePreviewDto sse_decode_file_preview_dto(SseDeserializer deserializer);

  @protected
  ForceResumeReportDto sse_decode_force_resume_report_dto(
    SseDeserializer deserializer,
  );

  @protected
  HistoryCacheStatusDto sse_decode_history_cache_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  HolderDto sse_decode_holder_dto(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AccountServiceDto> sse_decode_list_account_service_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AcpAgentDto> sse_decode_list_acp_agent_dto(SseDeserializer deserializer);

  @protected
  List<AcpAgentFlagDto> sse_decode_list_acp_agent_flag_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AcpAuthMethodDto> sse_decode_list_acp_auth_method_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AcpBinaryOverrideDto> sse_decode_list_acp_binary_override_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AcpCommandDto> sse_decode_list_acp_command_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AcpConfigOptionDto> sse_decode_list_acp_config_option_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AcpConfigValueDto> sse_decode_list_acp_config_value_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AcpCustomAgentDto> sse_decode_list_acp_custom_agent_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AcpDataModeDto> sse_decode_list_acp_data_mode_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AcpEnvVarDto> sse_decode_list_acp_env_var_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AcpGatewayDto> sse_decode_list_acp_gateway_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<AppServeStatusDto> sse_decode_list_app_serve_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<DirEntryDto> sse_decode_list_dir_entry_dto(SseDeserializer deserializer);

  @protected
  List<FileEntryDto> sse_decode_list_file_entry_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<HolderDto> sse_decode_list_holder_dto(SseDeserializer deserializer);

  @protected
  List<LocalSessionDto> sse_decode_list_local_session_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ModelInfoDto> sse_decode_list_model_info_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ServiceIdDto> sse_decode_list_service_id_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<SubStatusDto> sse_decode_list_sub_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ThreadItemDto> sse_decode_list_thread_item_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<ThreadMetaDto> sse_decode_list_thread_meta_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TurnItemsPageDto> sse_decode_list_turn_items_page_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<TurnSummaryDto> sse_decode_list_turn_summary_dto(
    SseDeserializer deserializer,
  );

  @protected
  LocalSessionDto sse_decode_local_session_dto(SseDeserializer deserializer);

  @protected
  LogLineDto sse_decode_log_line_dto(SseDeserializer deserializer);

  @protected
  ModelInfoDto sse_decode_model_info_dto(SseDeserializer deserializer);

  @protected
  OlderPageDto sse_decode_older_page_dto(SseDeserializer deserializer);

  @protected
  OpenCodeServeDto sse_decode_open_code_serve_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AccountUserDto? sse_decode_opt_box_autoadd_account_user_dto(
    SseDeserializer deserializer,
  );

  @protected
  AcpAuthDto? sse_decode_opt_box_autoadd_acp_auth_dto(
    SseDeserializer deserializer,
  );

  @protected
  AcpJobDto? sse_decode_opt_box_autoadd_acp_job_dto(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ThreadHistoryDto? sse_decode_opt_box_autoadd_thread_history_dto(
    SseDeserializer deserializer,
  );

  @protected
  ThreadRuntimeConfigDto? sse_decode_opt_box_autoadd_thread_runtime_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  ProjectConfigDto sse_decode_project_config_dto(SseDeserializer deserializer);

  @protected
  RetryProgressDto sse_decode_retry_progress_dto(SseDeserializer deserializer);

  @protected
  ServiceIdDto sse_decode_service_id_dto(SseDeserializer deserializer);

  @protected
  SessionFollowUpdateDto sse_decode_session_follow_update_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionLivenessDto sse_decode_session_liveness_dto(
    SseDeserializer deserializer,
  );

  @protected
  SubStatusDto sse_decode_sub_status_dto(SseDeserializer deserializer);

  @protected
  ThreadConfigDto sse_decode_thread_config_dto(SseDeserializer deserializer);

  @protected
  ThreadHistoryDto sse_decode_thread_history_dto(SseDeserializer deserializer);

  @protected
  ThreadItemDto sse_decode_thread_item_dto(SseDeserializer deserializer);

  @protected
  ThreadMetaDto sse_decode_thread_meta_dto(SseDeserializer deserializer);

  @protected
  ThreadRuntimeConfigDto sse_decode_thread_runtime_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  TurnItemsPageDto sse_decode_turn_items_page_dto(SseDeserializer deserializer);

  @protected
  TurnSummaryDto sse_decode_turn_summary_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WebLoginStartDto sse_decode_web_login_start_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_app_event_dto_Sse(
    RustStreamSink<AppEventDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_line_dto_Sse(
    RustStreamSink<LogLineDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_retry_progress_dto_Sse(
    RustStreamSink<RetryProgressDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_session_follow_update_dto_Sse(
    RustStreamSink<SessionFollowUpdateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_poll_dto(
    AccountPollDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_account_service_dto(
    AccountServiceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_account_user_dto(
    AccountUserDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_acp_agent_dto(AcpAgentDto self, SseSerializer serializer);

  @protected
  void sse_encode_acp_agent_flag_dto(
    AcpAgentFlagDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_acp_agents_dto(AcpAgentsDto self, SseSerializer serializer);

  @protected
  void sse_encode_acp_auth_dto(AcpAuthDto self, SseSerializer serializer);

  @protected
  void sse_encode_acp_auth_method_dto(
    AcpAuthMethodDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_acp_binary_override_dto(
    AcpBinaryOverrideDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_acp_command_dto(AcpCommandDto self, SseSerializer serializer);

  @protected
  void sse_encode_acp_config_option_dto(
    AcpConfigOptionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_acp_config_value_dto(
    AcpConfigValueDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_acp_custom_agent_dto(
    AcpCustomAgentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_acp_data_mode_dto(
    AcpDataModeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_acp_env_var_dto(AcpEnvVarDto self, SseSerializer serializer);

  @protected
  void sse_encode_acp_gateway_dto(AcpGatewayDto self, SseSerializer serializer);

  @protected
  void sse_encode_acp_job_dto(AcpJobDto self, SseSerializer serializer);

  @protected
  void sse_encode_acp_save_dto(AcpSaveDto self, SseSerializer serializer);

  @protected
  void sse_encode_acp_serve_dto(AcpServeDto self, SseSerializer serializer);

  @protected
  void sse_encode_acp_settings_dto(
    AcpSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_app_capabilities_dto(
    AppCapabilitiesDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_app_event_dto(AppEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_app_serve_dto(AppServeDto self, SseSerializer serializer);

  @protected
  void sse_encode_app_serve_status_dto(
    AppServeStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_account_user_dto(
    AccountUserDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_acp_auth_dto(
    AcpAuthDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_acp_custom_agent_dto(
    AcpCustomAgentDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_acp_job_dto(
    AcpJobDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_acp_settings_dto(
    AcpSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_thread_config_dto(
    ThreadConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_thread_history_dto(
    ThreadHistoryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_thread_runtime_config_dto(
    ThreadRuntimeConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_codex_auth_status_dto(
    CodexAuthStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_codex_login_start_dto(
    CodexLoginStartDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_codex_setup_status_dto(
    CodexSetupStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_config_view(ConfigView self, SseSerializer serializer);

  @protected
  void sse_encode_device_code_dto(DeviceCodeDto self, SseSerializer serializer);

  @protected
  void sse_encode_dir_entry_dto(DirEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_file_entry_dto(FileEntryDto self, SseSerializer serializer);

  @protected
  void sse_encode_file_preview_dto(
    FilePreviewDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_force_resume_report_dto(
    ForceResumeReportDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_history_cache_status_dto(
    HistoryCacheStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_holder_dto(HolderDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account_service_dto(
    List<AccountServiceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_acp_agent_dto(
    List<AcpAgentDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_acp_agent_flag_dto(
    List<AcpAgentFlagDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_acp_auth_method_dto(
    List<AcpAuthMethodDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_acp_binary_override_dto(
    List<AcpBinaryOverrideDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_acp_command_dto(
    List<AcpCommandDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_acp_config_option_dto(
    List<AcpConfigOptionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_acp_config_value_dto(
    List<AcpConfigValueDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_acp_custom_agent_dto(
    List<AcpCustomAgentDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_acp_data_mode_dto(
    List<AcpDataModeDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_acp_env_var_dto(
    List<AcpEnvVarDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_acp_gateway_dto(
    List<AcpGatewayDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_app_serve_status_dto(
    List<AppServeStatusDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dir_entry_dto(
    List<DirEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_entry_dto(
    List<FileEntryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_holder_dto(
    List<HolderDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_local_session_dto(
    List<LocalSessionDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_model_info_dto(
    List<ModelInfoDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_service_id_dto(
    List<ServiceIdDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sub_status_dto(
    List<SubStatusDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_thread_item_dto(
    List<ThreadItemDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_thread_meta_dto(
    List<ThreadMetaDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_turn_items_page_dto(
    List<TurnItemsPageDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_turn_summary_dto(
    List<TurnSummaryDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_session_dto(
    LocalSessionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_line_dto(LogLineDto self, SseSerializer serializer);

  @protected
  void sse_encode_model_info_dto(ModelInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_older_page_dto(OlderPageDto self, SseSerializer serializer);

  @protected
  void sse_encode_open_code_serve_dto(
    OpenCodeServeDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_account_user_dto(
    AccountUserDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_acp_auth_dto(
    AcpAuthDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_acp_job_dto(
    AcpJobDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_thread_history_dto(
    ThreadHistoryDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_thread_runtime_config_dto(
    ThreadRuntimeConfigDto? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_project_config_dto(
    ProjectConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_retry_progress_dto(
    RetryProgressDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_service_id_dto(ServiceIdDto self, SseSerializer serializer);

  @protected
  void sse_encode_session_follow_update_dto(
    SessionFollowUpdateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_liveness_dto(
    SessionLivenessDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sub_status_dto(SubStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_thread_config_dto(
    ThreadConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thread_history_dto(
    ThreadHistoryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thread_item_dto(ThreadItemDto self, SseSerializer serializer);

  @protected
  void sse_encode_thread_meta_dto(ThreadMetaDto self, SseSerializer serializer);

  @protected
  void sse_encode_thread_runtime_config_dto(
    ThreadRuntimeConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_turn_items_page_dto(
    TurnItemsPageDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_turn_summary_dto(
    TurnSummaryDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_web_login_start_dto(
    WebLoginStartDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
