// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_key`, `current_relay`

/// Initialise the engine with the platform app-support dir (from Dart's
/// path_provider). Must be called once after `RustLib.init()`.
Future<void> initBridge({required String supportDir}) =>
    RustLib.instance.api.crateApiBridgeInitBridge(supportDir: supportDir);

/// Current config view (relay + whether a key is set).
Future<ConfigView> getConfig() =>
    RustLib.instance.api.crateApiBridgeGetConfig();

/// Set the relay `host:port` and persist.
Future<void> setRelay({required String relay}) =>
    RustLib.instance.api.crateApiBridgeSetRelay(relay: relay);

/// Set the 32-byte MSG_HEADER_KEY and persist (validates length).
Future<void> setKey({required String key}) =>
    RustLib.instance.api.crateApiBridgeSetKey(key: key);

/// Import a `pcx1:` share string: decode, persist relay + key, return relay.
Future<String> importConfig({required String text}) =>
    RustLib.instance.api.crateApiBridgeImportConfig(text: text);

/// Export the current relay+key as a `pcx1:` share string.
Future<String> exportConfig() =>
    RustLib.instance.api.crateApiBridgeExportConfig();

/// Discover services on the configured relay (applies the stored key first).
Future<List<ServiceIdDto>> discoverServices() =>
    RustLib.instance.api.crateApiBridgeDiscoverServices();

/// Subscribe to an API service, exposing it on `127.0.0.1:<local_port>`.
Future<SubStatusDto> apiSubscribe({
  required String serviceKey,
  required int localPort,
}) => RustLib.instance.api.crateApiBridgeApiSubscribe(
  serviceKey: serviceKey,
  localPort: localPort,
);

/// Stop an API-service subscription.
Future<void> apiUnsubscribe({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeApiUnsubscribe(serviceKey: serviceKey);

/// List all active subscriptions.
Future<List<SubStatusDto>> subscriptions() =>
    RustLib.instance.api.crateApiBridgeSubscriptions();

/// View of persisted config for the UI; never exposes the raw key.
class ConfigView {
  /// Configured relay `host:port`, if any.
  final String? relay;

  /// Whether a 32-byte key is stored (value withheld).
  final bool hasKey;

  const ConfigView({this.relay, required this.hasKey});

  @override
  int get hashCode => relay.hashCode ^ hasKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigView &&
          runtimeType == other.runtimeType &&
          relay == other.relay &&
          hasKey == other.hasKey;
}

/// A discovered service, mirrored for Dart.
class ServiceIdDto {
  /// Device id segment.
  final String device;

  /// `app` or `api`.
  final String kind;

  /// Instance name segment.
  final String name;

  /// Full relay key.
  final String key;

  const ServiceIdDto({
    required this.device,
    required this.kind,
    required this.name,
    required this.key,
  });

  @override
  int get hashCode =>
      device.hashCode ^ kind.hashCode ^ name.hashCode ^ key.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServiceIdDto &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          kind == other.kind &&
          name == other.name &&
          key == other.key;
}

/// Status of one active subscription, mirrored for Dart.
class SubStatusDto {
  /// Service key.
  final String key;

  /// Local `host:port`.
  final String localAddr;

  /// Task still running.
  final bool alive;

  const SubStatusDto({
    required this.key,
    required this.localAddr,
    required this.alive,
  });

  @override
  int get hashCode => key.hashCode ^ localAddr.hashCode ^ alive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubStatusDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          localAddr == other.localAddr &&
          alive == other.alive;
}
