// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_key`, `current_relay`, `holder_dto`, `meta_follow_update_dto`, `meta_holder_dto`, `meta_liveness_dto`, `meta_thread_item_dto`, `project_config_dto`, `thread_config_dto`, `thread_config_from_dto`, `to_log_dto`

/// Initialise the engine with the platform app-support dir (from Dart's
/// path_provider). Must be called once after `RustLib.init()`.
Future<void> initBridge({required String supportDir}) =>
    RustLib.instance.api.crateApiBridgeInitBridge(supportDir: supportDir);

/// Current config view (relay/key presence, locale, and account state).
Future<ConfigView> getConfig() =>
    RustLib.instance.api.crateApiBridgeGetConfig();

/// Set the relay `host:port` and persist.
Future<void> setRelay({required String relay}) =>
    RustLib.instance.api.crateApiBridgeSetRelay(relay: relay);

/// Set the 32-byte MSG_HEADER_KEY and persist (validates length).
Future<void> setKey({required String key}) =>
    RustLib.instance.api.crateApiBridgeSetKey(key: key);

/// Set the UI locale (BCP-47, e.g. `en`/`zh`) and persist. An empty string
/// clears it, meaning the app follows the system locale.
Future<void> setLocale({required String locale}) =>
    RustLib.instance.api.crateApiBridgeSetLocale(locale: locale);

/// Detect whether the 自带 codex has a usable provider + credentials. Drives
/// the first-run setup wizard: `needs_setup` is `true` when neither a login nor
/// a custom provider is configured.
Future<CodexSetupStatusDto> codexSetupStatus() =>
    RustLib.instance.api.crateApiBridgeCodexSetupStatus();

/// Configure a minimal custom OpenAI-compatible provider (base URL + API key)
/// for the 自带 codex, writing `$CODEX_HOME/config.toml`. No `codex login` is
/// needed — the key rides as the provider's bearer token. `model` is optional
/// (defaults to a sensible model). Takes effect on the next hosting start.
Future<void> codexSetupProvider({
  required String baseUrl,
  required String apiKey,
  String? model,
}) => RustLib.instance.api.crateApiBridgeCodexSetupProvider(
  baseUrl: baseUrl,
  apiKey: apiKey,
  model: model,
);

/// The active 自带-codex system-prompt variant (`default` / `non_degraded` /
/// `custom`).
Future<String> codexPromptVariant() =>
    RustLib.instance.api.crateApiBridgeCodexPromptVariant();

/// Switch the 自带-codex system prompt. `non_degraded` swaps in the bundled
/// prompt that drops the commentary / intermediary-update mandates (which can
/// starve reasoning, see openai/codex#30364); `default` restores codex's
/// built-in prompt. Takes effect for threads started after the change.
Future<void> codexSetPromptVariant({required String variant}) =>
    RustLib.instance.api.crateApiBridgeCodexSetPromptVariant(variant: variant);

/// Begin codex's official ChatGPT login on the app-server behind `service_key`
/// (which must be a connected host). Tries the browser flow, falling back to
/// device code when codex can't bind its local callback port (`:1455`/`:1457`,
/// reserved on many Windows machines). codex writes `auth.json` itself —
/// Pocket- Codex never generates the credential. Poll [`codex_auth_status`]
/// until `authenticated`. The OAuth HTTP inherits the proxy the host was
/// started with, so a China-network user hosts with a proxy and login goes
/// through it.
Future<CodexLoginStartDto> codexLoginChatgptStart({
  required String serviceKey,
}) => RustLib.instance.api.crateApiBridgeCodexLoginChatgptStart(
  serviceKey: serviceKey,
);

/// Poll the codex auth status for the app-server behind `service_key`.
Future<CodexAuthStatusDto> codexAuthStatus({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeCodexAuthStatus(serviceKey: serviceKey);

/// Cancel an in-flight ChatGPT login (from [`codex_login_chatgpt_start`]).
Future<void> codexLoginCancel({
  required String serviceKey,
  required String loginId,
}) => RustLib.instance.api.crateApiBridgeCodexLoginCancel(
  serviceKey: serviceKey,
  loginId: loginId,
);

/// Sign the 自带 codex out (revoke + delete its `auth.json`) on `service_key`.
Future<void> codexLogout({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeCodexLogout(serviceKey: serviceKey);

/// Import a `pcx1:` share string: decode, persist relay + key, return relay.
Future<String> importConfig({required String text}) =>
    RustLib.instance.api.crateApiBridgeImportConfig(text: text);

/// Export the current relay+key as a `pcx1:` share string.
Future<String> exportConfig() =>
    RustLib.instance.api.crateApiBridgeExportConfig();

/// Discover services: in account mode from the backend (`/v1/services`), in
/// self-host mode from the relay (applying the stored key first).
Future<List<ServiceIdDto>> discoverServices() =>
    RustLib.instance.api.crateApiBridgeDiscoverServices();

/// Subscribe to an API service, exposing it on `127.0.0.1:<local_port>`.
Future<SubStatusDto> apiSubscribe({
  required String serviceKey,
  required int localPort,
}) => RustLib.instance.api.crateApiBridgeApiSubscribe(
  serviceKey: serviceKey,
  localPort: localPort,
);

/// Stop an API-service subscription.
Future<void> apiUnsubscribe({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeApiUnsubscribe(serviceKey: serviceKey);

/// List all active subscriptions.
Future<List<SubStatusDto>> subscriptions() =>
    RustLib.instance.api.crateApiBridgeSubscriptions();

/// The `deps/codex` commit the compiled-in (自带) codex app-server was built
/// from — its meaningful "version", since codex's own crate version is a
/// `0.0.0` placeholder. The host details show this for an embedded host.
Future<String> embeddedCodexVersion() =>
    RustLib.instance.api.crateApiBridgeEmbeddedCodexVersion();

/// Start hosting a local codex app-server **and** Responses API proxy under the
/// signed-in account, publishing both `app:<name>` and `api:<name>`. Re-hosting
/// a name whose codex is still alive just re-registers any dropped tunnels.
/// `proxy` is the upstream proxy both use to reach chatgpt.com (`None` =
/// inherit env). `embedded` runs codex's app-server in-process (the compiled-in
/// `embedded-codex`) instead of spawning an external binary — desktop only; the
/// `binary_override` is ignored when `embedded` is set. Desktop only.
Future<AppServeDto> appServeStart({
  required int port,
  String? binaryOverride,
  String? name,
  String? proxy,
  required bool embedded,
}) => RustLib.instance.api.crateApiBridgeAppServeStart(
  port: port,
  binaryOverride: binaryOverride,
  name: name,
  proxy: proxy,
  embedded: embedded,
);

/// Snapshot of every local host (for the status cards + periodic re-probe).
Future<List<AppServeStatusDto>> appServeStatus() =>
    RustLib.instance.api.crateApiBridgeAppServeStatus();

/// Take one tunnel (`kind` = `"app"`/`"api"`/`"meta"`) of a local host off the
/// relay without stopping the host — a reversible unpublish. The codex / API
/// proxy / meta service keep running; [`app_serve_reregister`] re-publishes it.
Future<void> appServeDeregister({required String name, required String kind}) =>
    RustLib.instance.api.crateApiBridgeAppServeDeregister(
      name: name,
      kind: kind,
    );

/// Re-publish a previously deregistered tunnel (`kind` = `"app"`/`"api"`/
/// `"meta"`) of a still-running local host.
Future<void> appServeReregister({required String name, required String kind}) =>
    RustLib.instance.api.crateApiBridgeAppServeReregister(
      name: name,
      kind: kind,
    );

/// Fully stop one local host by name (both tunnels + watchdog + API proxy, and
/// stops codex).
Future<void> appServeStop({required String name}) =>
    RustLib.instance.api.crateApiBridgeAppServeStop(name: name);

/// Stop every local host (called on app quit so a real quit leaves no orphan
/// codex). A no-op when nothing is hosting.
Future<void> appServeStopAll() =>
    RustLib.instance.api.crateApiBridgeAppServeStopAll();

/// The resolved `codex` binary path (persisted config → `$PATH`), or `None` so
/// the UI can prompt the user to point at one.
Future<String?> codexLocate() =>
    RustLib.instance.api.crateApiBridgeCodexLocate();

/// Connect to an app-server service: subscribe on `127.0.0.1:<local_port>`,
/// open the JSON-RPC websocket and run the `initialize` handshake. Idempotent.
Future<void> appConnect({required String serviceKey, required int localPort}) =>
    RustLib.instance.api.crateApiBridgeAppConnect(
      serviceKey: serviceKey,
      localPort: localPort,
    );

/// Whether a live app-server session exists for `service_key`.
bool appIsConnected({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppIsConnected(serviceKey: serviceKey);

/// Disconnect the app-server session and its pb-mapper subscription.
Future<void> appDisconnect({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppDisconnect(serviceKey: serviceKey);

/// Probe whether an app-server is actually REACHABLE — its backend responds to
/// a handshake — rather than merely registered on the relay. The services list
/// uses this so a registered-but-dead app-server (a live relay registrant
/// forwarding to a codex app-server that has died) shows as unreachable instead
/// of a false "online". Opens a transient tunnel + `initialize` with a timeout,
/// then tears it down; a live session short-circuits to `true`.
Future<bool> appProbe({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppProbe(serviceKey: serviceKey);

/// Why [`app_probe`] considers a service unreachable, or `None` when it is
/// reachable.
///
/// A bare `false` made the UI say "the app-server did not respond", which is
/// wrong whenever the tunnel DID answer and refused us — a relay rejecting the
/// handshake (missing or stale authentication code) is the common case, and it
/// needs a different fix from a dead backend. This hands the transport's own
/// words to the UI so it can name the actual problem.
Future<String?> appProbeReason({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppProbeReason(serviceKey: serviceKey);

/// Probe whether an API proxy is actually REACHABLE — its host answers a
/// minimal HTTP request — rather than merely registered on the relay. The
/// services list uses this so a registered-but-dead API proxy (a live relay
/// registrant forwarding to an api-proxy that has died) shows unreachable
/// instead of a false "online", matching the app-server's [`app_probe`]. Opens
/// a transient tunnel, hits the proxy's local 403 fallback (no upstream model
/// call), then tears it down.
Future<bool> apiProbe({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeApiProbe(serviceKey: serviceKey);

/// Health-check an app-server THIS machine hosts itself, by its loopback
/// app-listen address (e.g. `127.0.0.1:18080`) — a direct `initialize`
/// handshake with no relay hop. Unlike a bare port-open check this catches a
/// wedged / half-open codex (the listener still `accept`s but never answers
/// RPC), so a locally-hosted server that has silently stopped serving reads
/// `false` instead of a false "running". Fast because it stays on loopback.
Future<bool> appProbeLocal({required String localAddr}) =>
    RustLib.instance.api.crateApiBridgeAppProbeLocal(localAddr: localAddr);

/// Health-check an API proxy THIS machine hosts itself, by its loopback
/// api-listen address — a direct minimal HTTP request, no relay hop. Lets a
/// local host's API tunnel read "online" the instant its proxy is up instead
/// of waiting on a slower transient relay round-trip. Mirrors
/// [`app_probe_local`].
Future<bool> apiProbeLocal({required String localAddr}) =>
    RustLib.instance.api.crateApiBridgeApiProbeLocal(localAddr: localAddr);

/// Stream captured `tracing` events for the in-app log viewer: the retained
/// recent history (oldest first) followed by every new event live, until the
/// Dart side drops the stream. Subscribes before replaying history so nothing
/// is missed in between (a line captured right at that boundary may appear
/// twice — harmless for a log tail).
Stream<LogLineDto> logEvents() =>
    RustLib.instance.api.crateApiBridgeLogEvents();

/// Stream retry progress for host meta requests, so the UI can show "retrying
/// 2/10" instead of appearing frozen through the backoff.
///
/// Notifications only — the request's own success or failure is still delivered
/// by whichever call the UI made. A dropped tick is harmless (a newer one
/// supersedes it), so lag is skipped rather than treated as an error.
Stream<RetryProgressDto> metaRetryEvents() =>
    RustLib.instance.api.crateApiBridgeMetaRetryEvents();

/// Stream live app-server events (turn/item notifications) for `service_key`.
/// The Dart side receives one [`AppEventDto`] per notification until the
/// session is disconnected.
Stream<AppEventDto> appEvents({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppEvents(serviceKey: serviceKey);

/// List threads known to the app-server.
Future<List<ThreadMetaDto>> appThreadList({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppThreadList(serviceKey: serviceKey);

/// List the models the app-server offers.
Future<List<ModelInfoDto>> appModelList({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppModelList(serviceKey: serviceKey);

/// Start a new thread / project. `approval_policy` is one of
/// `untrusted` / `on-failure` / `on-request` / `never`; `sandbox` is one of
/// `read-only` / `workspace-write` / `danger-full-access`. Returns the id.
Future<String> appThreadStart({
  required String serviceKey,
  String? model,
  String? cwd,
  String? approvalPolicy,
  String? sandbox,
}) => RustLib.instance.api.crateApiBridgeAppThreadStart(
  serviceKey: serviceKey,
  model: model,
  cwd: cwd,
  approvalPolicy: approvalPolicy,
  sandbox: sandbox,
);

/// Answer a server approval request. `decision` is the wire value the session
/// layer recognises: `accept` or `acceptForSession` to grant, any other value
/// (e.g. `decline`) to decline.
Future<void> appRespondApproval({
  required String serviceKey,
  required String requestId,
  required String decision,
}) => RustLib.instance.api.crateApiBridgeAppRespondApproval(
  serviceKey: serviceKey,
  requestId: requestId,
  decision: decision,
);

/// Answer an `item/tool/requestUserInput` elicitation (the model asking the
/// user structured questions, NOT a command/file approval). `answers_json` is a
/// JSON object mapping each question id to its chosen answer string(s) (option
/// labels and/or free-text), e.g. `{"theme":["山水抒怀"]}`; an empty object
/// `{}` cancels. The session layer wraps it into the protocol's
/// `ToolRequestUserInputResponse` so the model actually receives the user's
/// selections.
Future<void> appRespondUserInput({
  required String serviceKey,
  required String requestId,
  required String answersJson,
}) => RustLib.instance.api.crateApiBridgeAppRespondUserInput(
  serviceKey: serviceKey,
  requestId: requestId,
  answersJson: answersJson,
);

/// Resume an existing thread (load it into the session) before reading it or
/// sending turns; otherwise the server reports "thread not found".
Future<void> appThreadResume({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeAppThreadResume(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Read a thread's conversation items (oldest first) and whether a turn is
/// still running, so re-opening an in-flight thread restores live state.
Future<ThreadHistoryDto> appThreadRead({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeAppThreadRead(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// The latest server-reported runtime config for a thread (from its
/// start/resume response, kept fresh by live `thread/settings/updated`
/// notifications), or `None` when the server hasn't reported any. Reads the
/// engine cache only — no RPC — so the UI can poll it cheaply after a send.
ThreadRuntimeConfigDto? appThreadRuntimeConfig({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeAppThreadRuntimeConfig(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Read the account rate-limit / quota snapshot as raw JSON (5h + weekly
/// windows). Parsed on the Dart side since the shape is nested and volatile.
Future<String> appRateLimits({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppRateLimits(serviceKey: serviceKey);

/// Unified diff of the repo at `cwd` vs its remote default branch. Empty when
/// the cwd isn't a git repo or there are no changes.
Future<String> appGitDiff({required String serviceKey, required String cwd}) =>
    RustLib.instance.api.crateApiBridgeAppGitDiff(
      serviceKey: serviceKey,
      cwd: cwd,
    );

/// Start a manual conversation compaction; the server emits `thread/compacted`
/// when done.
Future<void> appCompact({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeAppCompact(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// A one-line gist of where a thread got to (the opening sentence of its most
/// recent agent message), or `None` when it has produced none.
///
/// Its own call rather than a field on [`app_thread_list`] because the upstream
/// `thread/list` carries no summary: the only source is a full `thread/read`,
/// so the UI fetches these lazily for the rows it actually shows instead of
/// paying for every conversation up front.
Future<String?> appThreadSummary({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeAppThreadSummary(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Rename a conversation. The title is persisted by the app-server (so it
/// follows the thread across devices); an empty `name` clears it, and the UI
/// falls back to the thread preview.
Future<void> appSetThreadName({
  required String serviceKey,
  required String threadId,
  required String name,
}) => RustLib.instance.api.crateApiBridgeAppSetThreadName(
  serviceKey: serviceKey,
  threadId: threadId,
  name: name,
);

/// Send a user message (text and/or attached images), starting a model turn.
/// `images` are `data:image/...;base64,...` URLs — the wire form that reaches
/// BOTH local and relay-tunneled remote app-servers (a host filesystem path
/// would not); pass an empty list for a text-only turn, and text may be empty
/// when at least one image is attached. `model` / `approval_policy` /
/// `sandbox` are optional per-turn overrides (apply to this and subsequent
/// turns) so model and permission can change mid-conversation.
/// `collaboration_mode` ("plan" / "default", or null to leave unchanged) is
/// sticky on the thread, so pass "default" to leave plan mode.
/// `reasoning_effort` ("low"/"medium"/"high", or null for the model default) is
/// the "thinking level" for this turn. The reply streams via [`app_events`];
/// this returns once the turn is accepted.
Future<void> appTurnStart({
  required String serviceKey,
  required String threadId,
  required String text,
  required List<String> images,
  String? model,
  String? approvalPolicy,
  String? sandbox,
  String? collaborationMode,
  String? reasoningEffort,
}) => RustLib.instance.api.crateApiBridgeAppTurnStart(
  serviceKey: serviceKey,
  threadId: threadId,
  text: text,
  images: images,
  model: model,
  approvalPolicy: approvalPolicy,
  sandbox: sandbox,
  collaborationMode: collaborationMode,
  reasoningEffort: reasoningEffort,
);

/// Interrupt the running turn. `turn_id` (from the latest `turn/started`) is
/// required by the server; pass null only if unknown.
Future<void> appTurnInterrupt({
  required String serviceKey,
  required String threadId,
  String? turnId,
}) => RustLib.instance.api.crateApiBridgeAppTurnInterrupt(
  serviceKey: serviceKey,
  threadId: threadId,
  turnId: turnId,
);

/// List every codex session under the shared `CODEX_HOME`, newest first,
/// each annotated with whether it is safe to resume.
///
/// Works without any app-server connection — it reads the local rollout
/// files and process table directly, so it surfaces sessions created by
/// *other* codex clients (the desktop app, the CLI, the VS Code
/// extension) that share this `CODEX_HOME`. Meaningful only when the UI
/// runs on the same machine as those sessions.
Future<List<LocalSessionDto>> appLocalSessions() =>
    RustLib.instance.api.crateApiBridgeAppLocalSessions();

/// Inspect one session's current resume-safety and the processes a force
/// takeover would evict. Poll this before showing a resume button so the
/// UI reflects live ownership (a session can flip between read-only and
/// resumable as the desktop app loads / releases it).
Future<SessionLivenessDto> appSessionLiveness({required String threadId}) =>
    RustLib.instance.api.crateApiBridgeAppSessionLiveness(threadId: threadId);

/// Read a local session's transcript for READ-ONLY viewing. Parses the
/// on-disk rollout directly (no app-server connection, no resume, no write),
/// so it works even while another codex client still owns the session.
/// Items are in the same shape as [`app_thread_read`], so the read-only
/// viewer reuses the live-conversation rendering. Poll it alongside
/// [`app_session_liveness`] to follow a running session and notice when it
/// goes idle (resume-eligible).
Future<List<ThreadItemDto>> appLocalSessionTranscript({
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeAppLocalSessionTranscript(
  threadId: threadId,
);

/// Force-resume a session into the app-server behind `service_key`.
///
/// Best-effort terminates every live process holding the session's rollout
/// open (never Pocket-Codex's own app-server), then issues `thread/resume`
/// regardless of the eviction outcome. The UI must gate this on explicit
/// user confirmation and must not offer it while a turn is actively
/// running (`SessionLivenessDto::allows_resume == false`). The returned
/// report says exactly which processes were killed / survived and whether
/// the resume took.
Future<ForceResumeReportDto> appForceResume({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeAppForceResume(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Remote analogue of [`app_local_sessions`]: list the sessions of the host
/// behind `service_key` via its meta tunnel (loopback when this app is the
/// host, broker when remote). Lets a phone see a desktop host's sessions —
/// including those owned by another codex client.
Future<List<LocalSessionDto>> metaSessions({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeMetaSessions(serviceKey: serviceKey);

/// Remote analogue of [`app_session_liveness`].
Future<SessionLivenessDto> metaSessionLiveness({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeMetaSessionLiveness(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Subscribe to live read-only transcript + ownership snapshots for a session
/// held by another app-server. One long-lived meta response replaces client
/// polling; dropping the Dart stream stops forwarding.
Stream<SessionFollowUpdateDto> metaSessionEvents({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeMetaSessionEvents(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Remote analogue of [`app_local_session_transcript`].
Future<List<ThreadItemDto>> metaSessionTranscript({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeMetaSessionTranscript(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Remote analogue of [`app_force_resume`]: the host evicts the rollout's live
/// holders and resumes it into its colocated app-server over loopback. The UI
/// must gate this on explicit confirmation and not offer it while a turn runs.
Future<ForceResumeReportDto> metaForceResume({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeMetaForceResume(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Upload a document/file attachment to the host behind `service_key` (over
/// its meta tunnel — loopback when this app is the host), returning the
/// absolute HOST filesystem path where it was stored. The turn text then
/// references that path so the agent reads the file with its own tools —
/// codex's native host-file workflow (its input protocol carries only text
/// and images inline; there is no document slot).
Future<String> metaUploadFile({
  required String serviceKey,
  required String fileName,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiBridgeMetaUploadFile(
  serviceKey: serviceKey,
  fileName: fileName,
  bytes: bytes,
);

/// Read a thread's persisted config from the host behind `service_key`.
Future<ThreadConfigDto> metaThreadConfigGet({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeMetaThreadConfigGet(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Persist a thread's config on the host behind `service_key`; returns the
/// stored value.
Future<ThreadConfigDto> metaThreadConfigSet({
  required String serviceKey,
  required String threadId,
  required ThreadConfigDto config,
}) => RustLib.instance.api.crateApiBridgeMetaThreadConfigSet(
  serviceKey: serviceKey,
  threadId: threadId,
  config: config,
);

/// Read the project-folder config of the host behind `service_key`.
Future<ProjectConfigDto> metaProjectConfig({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeMetaProjectConfig(
      serviceKey: serviceKey,
    );

/// Replace the project-folder config of the host behind `service_key`; returns
/// the stored value. The desktop host edits this over its own loopback tunnel.
Future<ProjectConfigDto> metaSetProjectConfig({
  required String serviceKey,
  required List<String> projectRoots,
  String? defaultProject,
}) => RustLib.instance.api.crateApiBridgeMetaSetProjectConfig(
  serviceKey: serviceKey,
  projectRoots: projectRoots,
  defaultProject: defaultProject,
);

/// List the sub-directories of `path` on the host behind `service_key`, for the
/// remote project-folder browser. Errors (with a `403`-carrying message) if
/// `path` is outside the host's configured project roots.
Future<List<DirEntryDto>> metaListDir({
  required String serviceKey,
  required String path,
}) => RustLib.instance.api.crateApiBridgeMetaListDir(
  serviceKey: serviceKey,
  path: path,
);

/// List the files (not sub-directories) in `path` on the host behind
/// `service_key`, for the file-transfer panel. Errors (with a `403`-carrying
/// message) if `path` is outside the host's configured project roots.
Future<List<FileEntryDto>> metaListFiles({
  required String serviceKey,
  required String path,
}) => RustLib.instance.api.crateApiBridgeMetaListFiles(
  serviceKey: serviceKey,
  path: path,
);

/// Download a host file's raw bytes (root-confined) from the host behind
/// `service_key`, for saving to the controller's local disk. Errors (with a
/// `403`-carrying message) if `path` is outside the configured project roots.
Future<Uint8List> metaReadFile({
  required String serviceKey,
  required String path,
}) => RustLib.instance.api.crateApiBridgeMetaReadFile(
  serviceKey: serviceKey,
  path: path,
);

/// Read an image that `thread_id`'s transcript already references, so the UI
/// can render it inline instead of naming it. NOT root-confined: the host
/// authorises the read against that thread's own user messages, which is what
/// makes a pasted screenshot in the OS temp directory visible to a remote
/// controller without granting it a general file read. Errors (with a
/// `403`-carrying message) for a path the transcript never mentioned.
Future<Uint8List> metaReadThreadImage({
  required String serviceKey,
  required String threadId,
  required String path,
}) => RustLib.instance.api.crateApiBridgeMetaReadThreadImage(
  serviceKey: serviceKey,
  threadId: threadId,
  path: path,
);

/// Upload local `bytes` as `file_name` into host directory `dir`
/// (root-confined) on the host behind `service_key`; returns the absolute HOST
/// path where it landed. Never overwrites an existing same-named file (a
/// collision surfaces the host's `409` in the returned message).
Future<String> metaWriteFile({
  required String serviceKey,
  required String dir,
  required String fileName,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiBridgeMetaWriteFile(
  serviceKey: serviceKey,
  dir: dir,
  fileName: fileName,
  bytes: bytes,
);

/// Begin a GitHub device-flow login. `backend` overrides the configured /
/// default backend (and is remembered on success).
Future<DeviceCodeDto> accountLoginStart({String? backend}) =>
    RustLib.instance.api.crateApiBridgeAccountLoginStart(backend: backend);

/// Poll a device flow once. On `authorized` the session is persisted and the
/// app switches to account mode.
Future<AccountPollDto> accountLoginPoll({
  required String pollHandle,
  required String backend,
}) => RustLib.instance.api.crateApiBridgeAccountLoginPoll(
  pollHandle: pollHandle,
  backend: backend,
);

/// Begin a web (browser-redirect) GitHub login. `redirect_uri` is the
/// platform-specific callback the browser returns to (the app's custom scheme
/// on mobile, a loopback URL on desktop). `backend` overrides the configured /
/// default backend (and is remembered on a successful exchange).
Future<WebLoginStartDto> accountWebLoginStart({
  required String redirectUri,
  String? backend,
}) => RustLib.instance.api.crateApiBridgeAccountWebLoginStart(
  redirectUri: redirectUri,
  backend: backend,
);

/// Redeem the one-time `exchange_code` (with its PKCE `code_verifier`) from the
/// browser redirect. On success the session is persisted and the app switches
/// to account mode. Returns the signed-in identity.
Future<AccountUserDto> accountWebLoginExchange({
  required String exchangeCode,
  required String codeVerifier,
  required String backend,
}) => RustLib.instance.api.crateApiBridgeAccountWebLoginExchange(
  exchangeCode: exchangeCode,
  codeVerifier: codeVerifier,
  backend: backend,
);

/// The signed-in user (verified against the backend), or `None` if not signed
/// in.
Future<AccountUserDto?> accountCurrentUser() =>
    RustLib.instance.api.crateApiBridgeAccountCurrentUser();

/// Sign out: revoke the refresh token (best effort) and clear the local
/// session.
Future<void> accountLogout() =>
    RustLib.instance.api.crateApiBridgeAccountLogout();

/// List the account's services from the backend.
Future<List<AccountServiceDto>> accountServices() =>
    RustLib.instance.api.crateApiBridgeAccountServices();

/// Deregister one of the account's services from the relay (best-effort; a
/// still-running host re-registers shortly after). `kind` is `"app"` or
/// `"api"`.
Future<void> accountDeregisterService({
  required String device,
  required String kind,
  required String name,
}) => RustLib.instance.api.crateApiBridgeAccountDeregisterService(
  device: device,
  kind: kind,
  name: name,
);

/// Outcome of one device-flow poll, mirrored for Dart. `status` is one of
/// `pending` / `slow_down` / `authorized` / `expired` / `denied`; `login` is
/// set only when `authorized`.
class AccountPollDto {
  /// Poll status string.
  final String status;

  /// Signed-in login, when `status == "authorized"`.
  final String? login;

  /// GitHub account id, when authorized and known.
  final String? accountId;

  const AccountPollDto({required this.status, this.login, this.accountId});

  @override
  int get hashCode => status.hashCode ^ login.hashCode ^ accountId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountPollDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          login == other.login &&
          accountId == other.accountId;
}

/// One service in the account, mirrored for Dart (the `pcxu:` prefix stripped).
class AccountServiceDto {
  /// Device id segment.
  final String device;

  /// `app` or `api`.
  final String kind;

  /// Instance name segment.
  final String name;

  const AccountServiceDto({
    required this.device,
    required this.kind,
    required this.name,
  });

  @override
  int get hashCode => device.hashCode ^ kind.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountServiceDto &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          kind == other.kind &&
          name == other.name;
}

/// Signed-in identity mirrored for Dart.
class AccountUserDto {
  /// GitHub login/handle.
  final String login;

  /// GitHub account id, if known.
  final String? accountId;

  const AccountUserDto({required this.login, this.accountId});

  @override
  int get hashCode => login.hashCode ^ accountId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountUserDto &&
          runtimeType == other.runtimeType &&
          login == other.login &&
          accountId == other.accountId;
}

/// One app-server event mirrored for Dart. `kind` is the JSON-RPC method
/// (e.g. `turn/started`, `item/agentMessage/delta`, `turn/completed`).
class AppEventDto {
  /// JSON-RPC method name of the originating notification.
  final String kind;

  /// Thread id the event belongs to, when present.
  final String? threadId;

  /// Item id the event refers to, when present.
  final String? itemId;

  /// Item type tag when this event carries an item (`agentMessage`,
  /// `commandExecution`, `webSearch`, `mcpToolCall`, `fileChange`,
  /// `reasoning`, …); `None` for turn-level events.
  final String? itemType;

  /// One-line summary for tool/activity items (command, query, tool name…).
  final String? title;

  /// Text payload (a streaming delta or an item's body/detail).
  final String? text;

  /// Image URLs attached to a `userMessage` item: `data:image/...` URLs
  /// render inline; a host-local path (from a `localImage` input) renders as
  /// a filename chip. Empty for every other event.
  final List<String> images;

  /// Token to answer a server approval request via [`app_respond_approval`];
  /// `None` for ordinary notifications.
  final String? requestId;

  /// Full params JSON for fields not modelled above.
  final String raw;

  const AppEventDto({
    required this.kind,
    this.threadId,
    this.itemId,
    this.itemType,
    this.title,
    this.text,
    required this.images,
    this.requestId,
    required this.raw,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      threadId.hashCode ^
      itemId.hashCode ^
      itemType.hashCode ^
      title.hashCode ^
      text.hashCode ^
      images.hashCode ^
      requestId.hashCode ^
      raw.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          threadId == other.threadId &&
          itemId == other.itemId &&
          itemType == other.itemType &&
          title == other.title &&
          text == other.text &&
          images == other.images &&
          requestId == other.requestId &&
          raw == other.raw;
}

/// Result of starting local hosting, mirrored for Dart. One host publishes two
/// tunnels (`app:<name>` remote control + `api:<name>` Responses proxy).
class AppServeDto {
  /// Device id both services registered under.
  final String device;

  /// Service instance name (shared by the app + api tunnels).
  final String name;

  /// `pcx:<device>:app:<name>` key (what discovery + `app_connect` use).
  final String appServiceKey;

  /// Loopback `host:port` codex is listening on.
  final String appListenAddr;

  /// `pcx:<device>:api:<name>` key (what an `api connect` resolves).
  final String apiServiceKey;

  /// Loopback `host:port` the in-app Responses API proxy is listening on.
  final String apiListenAddr;

  /// `pcx:<device>:meta:<name>` key (the host meta service tunnel).
  final String metaServiceKey;

  /// Loopback `host:port` the in-app meta service is listening on.
  final String metaListenAddr;

  /// The codex process id.
  final int pid;

  /// Whether an already-running host was reused instead of freshly spawned.
  final bool reused;

  const AppServeDto({
    required this.device,
    required this.name,
    required this.appServiceKey,
    required this.appListenAddr,
    required this.apiServiceKey,
    required this.apiListenAddr,
    required this.metaServiceKey,
    required this.metaListenAddr,
    required this.pid,
    required this.reused,
  });

  @override
  int get hashCode =>
      device.hashCode ^
      name.hashCode ^
      appServiceKey.hashCode ^
      appListenAddr.hashCode ^
      apiServiceKey.hashCode ^
      apiListenAddr.hashCode ^
      metaServiceKey.hashCode ^
      metaListenAddr.hashCode ^
      pid.hashCode ^
      reused.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppServeDto &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          name == other.name &&
          appServiceKey == other.appServiceKey &&
          appListenAddr == other.appListenAddr &&
          apiServiceKey == other.apiServiceKey &&
          apiListenAddr == other.apiListenAddr &&
          metaServiceKey == other.metaServiceKey &&
          metaListenAddr == other.metaListenAddr &&
          pid == other.pid &&
          reused == other.reused;
}

/// Status of one local host, mirrored for Dart. Each host carries both tunnels'
/// publish state so the UI can offer per-tunnel 注销 / 重新注册.
class AppServeStatusDto {
  /// Service instance name.
  final String name;

  /// Device id.
  final String device;

  /// codex process id.
  final int? pid;

  /// codex is accepting on its listen port.
  final bool alive;

  /// Loopback `host:port` codex listens on.
  final String appListenAddr;

  /// `pcx:<device>:app:<name>` key.
  final String appServiceKey;

  /// The app tunnel is currently published.
  final bool appRegistered;

  /// Loopback `host:port` the API proxy listens on.
  final String apiListenAddr;

  /// `pcx:<device>:api:<name>` key.
  final String apiServiceKey;

  /// The api tunnel is currently published.
  final bool apiRegistered;

  /// Loopback `host:port` the meta service listens on.
  final String metaListenAddr;

  /// `pcx:<device>:meta:<name>` key.
  final String metaServiceKey;

  /// The meta tunnel is currently published.
  final bool metaRegistered;

  /// This host runs codex IN-PROCESS (the compiled-in `embedded-codex`)
  /// rather than a spawned external binary.
  final bool embedded;

  /// The resolved external codex binary path, or `None` for an embedded host.
  final String? codexBinary;

  /// Upstream proxy codex + the API proxy were started with, or `None` when
  /// they inherit the app's environment.
  final String? proxy;

  const AppServeStatusDto({
    required this.name,
    required this.device,
    this.pid,
    required this.alive,
    required this.appListenAddr,
    required this.appServiceKey,
    required this.appRegistered,
    required this.apiListenAddr,
    required this.apiServiceKey,
    required this.apiRegistered,
    required this.metaListenAddr,
    required this.metaServiceKey,
    required this.metaRegistered,
    required this.embedded,
    this.codexBinary,
    this.proxy,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      device.hashCode ^
      pid.hashCode ^
      alive.hashCode ^
      appListenAddr.hashCode ^
      appServiceKey.hashCode ^
      appRegistered.hashCode ^
      apiListenAddr.hashCode ^
      apiServiceKey.hashCode ^
      apiRegistered.hashCode ^
      metaListenAddr.hashCode ^
      metaServiceKey.hashCode ^
      metaRegistered.hashCode ^
      embedded.hashCode ^
      codexBinary.hashCode ^
      proxy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppServeStatusDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          device == other.device &&
          pid == other.pid &&
          alive == other.alive &&
          appListenAddr == other.appListenAddr &&
          appServiceKey == other.appServiceKey &&
          appRegistered == other.appRegistered &&
          apiListenAddr == other.apiListenAddr &&
          apiServiceKey == other.apiServiceKey &&
          apiRegistered == other.apiRegistered &&
          metaListenAddr == other.metaListenAddr &&
          metaServiceKey == other.metaServiceKey &&
          metaRegistered == other.metaRegistered &&
          embedded == other.embedded &&
          codexBinary == other.codexBinary &&
          proxy == other.proxy;
}

/// codex auth status for the app-server behind `service_key`, mirrored for
/// Dart.
class CodexAuthStatusDto {
  /// Signed in (a credential is active).
  final bool authenticated;

  /// Method when signed in (`chatgpt` / `apikey` / …).
  final String? method;

  const CodexAuthStatusDto({required this.authenticated, this.method});

  @override
  int get hashCode => authenticated.hashCode ^ method.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CodexAuthStatusDto &&
          runtimeType == other.runtimeType &&
          authenticated == other.authenticated &&
          method == other.method;
}

/// A started ChatGPT login on the 自带 codex, mirrored for Dart. `mode` is
/// `"browser"` (open `auth_url`) or `"device"` (open `verification_url` and
/// enter `user_code`) — codex falls back to device code when it can't bind its
/// local OAuth callback port.
class CodexLoginStartDto {
  /// `"browser"` or `"device"`.
  final String mode;

  /// Opaque id to pass back to [`codex_login_cancel`].
  final String loginId;

  /// Browser flow: OAuth URL to open. `None` for device flow.
  final String? authUrl;

  /// Device flow: URL to open. `None` for browser flow.
  final String? verificationUrl;

  /// Device flow: one-time code to enter. `None` for browser flow.
  final String? userCode;

  const CodexLoginStartDto({
    required this.mode,
    required this.loginId,
    this.authUrl,
    this.verificationUrl,
    this.userCode,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      loginId.hashCode ^
      authUrl.hashCode ^
      verificationUrl.hashCode ^
      userCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CodexLoginStartDto &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          loginId == other.loginId &&
          authUrl == other.authUrl &&
          verificationUrl == other.verificationUrl &&
          userCode == other.userCode;
}

/// What the 自带 codex has on disk in `CODEX_HOME`, for the onboarding wizard.
class CodexSetupStatusDto {
  /// Resolved `CODEX_HOME` (display path).
  final String codexHome;

  /// `config.toml` exists.
  final bool hasConfig;

  /// A credential exists (`auth.json` or `CODEX_ACCESS_TOKEN`).
  final bool hasAuth;

  /// A non-OpenAI custom provider is configured (authorizes turns on its
  /// own).
  final bool hasCustomProvider;

  /// `auth.json`'s `auth_mode` (`apikey` / `chatgpt` / …), when present.
  final String? authMode;

  /// Nothing lets codex authenticate yet → show the setup wizard.
  final bool needsSetup;

  /// Active system-prompt variant (`default` / `non_degraded` / `custom`).
  final String promptVariant;

  const CodexSetupStatusDto({
    required this.codexHome,
    required this.hasConfig,
    required this.hasAuth,
    required this.hasCustomProvider,
    this.authMode,
    required this.needsSetup,
    required this.promptVariant,
  });

  @override
  int get hashCode =>
      codexHome.hashCode ^
      hasConfig.hashCode ^
      hasAuth.hashCode ^
      hasCustomProvider.hashCode ^
      authMode.hashCode ^
      needsSetup.hashCode ^
      promptVariant.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CodexSetupStatusDto &&
          runtimeType == other.runtimeType &&
          codexHome == other.codexHome &&
          hasConfig == other.hasConfig &&
          hasAuth == other.hasAuth &&
          hasCustomProvider == other.hasCustomProvider &&
          authMode == other.authMode &&
          needsSetup == other.needsSetup &&
          promptVariant == other.promptVariant;
}

/// View of persisted config for the UI; never exposes the raw key or token.
class ConfigView {
  /// Configured relay `host:port`, if any.
  final String? relay;

  /// Whether a 32-byte key is stored (value withheld).
  final bool hasKey;

  /// Configured UI locale (BCP-47, e.g. `en`/`zh`), or `None` to follow
  /// the system locale.
  final String? locale;

  /// Active transport mode: `account` / `self_host` / `unconfigured`.
  final String mode;

  /// Signed-in GitHub login (account mode), if any.
  final String? accountLogin;

  /// Whether an account session token is stored (value withheld).
  final bool hasAccountToken;

  const ConfigView({
    this.relay,
    required this.hasKey,
    this.locale,
    required this.mode,
    this.accountLogin,
    required this.hasAccountToken,
  });

  @override
  int get hashCode =>
      relay.hashCode ^
      hasKey.hashCode ^
      locale.hashCode ^
      mode.hashCode ^
      accountLogin.hashCode ^
      hasAccountToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigView &&
          runtimeType == other.runtimeType &&
          relay == other.relay &&
          hasKey == other.hasKey &&
          locale == other.locale &&
          mode == other.mode &&
          accountLogin == other.accountLogin &&
          hasAccountToken == other.hasAccountToken;
}

/// A started device flow, mirrored for Dart: show the code + URL, then poll.
class DeviceCodeDto {
  /// Code the user types at [`Self::verification_uri`].
  final String userCode;

  /// URL the user opens to enter the code.
  final String verificationUri;

  /// Opaque handle passed back to [`account_login_poll`].
  final String pollHandle;

  /// Minimum seconds between polls.
  final BigInt intervalSecs;

  /// Seconds until the flow expires.
  final BigInt expiresInSecs;

  /// Resolved backend base URL to echo back to [`account_login_poll`].
  final String backend;

  const DeviceCodeDto({
    required this.userCode,
    required this.verificationUri,
    required this.pollHandle,
    required this.intervalSecs,
    required this.expiresInSecs,
    required this.backend,
  });

  @override
  int get hashCode =>
      userCode.hashCode ^
      verificationUri.hashCode ^
      pollHandle.hashCode ^
      intervalSecs.hashCode ^
      expiresInSecs.hashCode ^
      backend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceCodeDto &&
          runtimeType == other.runtimeType &&
          userCode == other.userCode &&
          verificationUri == other.verificationUri &&
          pollHandle == other.pollHandle &&
          intervalSecs == other.intervalSecs &&
          expiresInSecs == other.expiresInSecs &&
          backend == other.backend;
}

/// One browsable child directory of a host folder (mirrored for Dart).
class DirEntryDto {
  /// The directory's own name (final path component).
  final String name;

  /// Absolute host path, ready to browse into or use as a session's cwd.
  final String path;

  /// Whether the directory is a git repository (a project hint).
  final bool isGitRepo;

  const DirEntryDto({
    required this.name,
    required this.path,
    required this.isGitRepo,
  });

  @override
  int get hashCode => name.hashCode ^ path.hashCode ^ isGitRepo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DirEntryDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isGitRepo == other.isGitRepo;
}

/// One file in a host directory (mirrored for Dart), with size + mtime for the
/// file-transfer panel.
class FileEntryDto {
  /// The file's own name (final path component).
  final String name;

  /// Absolute host path.
  final String path;

  /// Size in bytes.
  final BigInt size;

  /// Last-modified time in unix seconds (0 when unavailable).
  final PlatformInt64 mtime;

  const FileEntryDto({
    required this.name,
    required this.path,
    required this.size,
    required this.mtime,
  });

  @override
  int get hashCode =>
      name.hashCode ^ path.hashCode ^ size.hashCode ^ mtime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileEntryDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          size == other.size &&
          mtime == other.mtime;
}

/// Outcome of a force-resume, mirrored for Dart.
class ForceResumeReportDto {
  /// Holders that were successfully terminated.
  final List<HolderDto> killed;

  /// Holders the kill could not reach.
  final List<HolderDto> survived;

  /// Whether the rollout is still held open after the attempt (the resume
  /// proceeded regardless).
  final bool stillHeld;

  /// Whether the subsequent `thread/resume` succeeded.
  final bool resumed;

  /// The resume error message, when `resumed` is false.
  final String? resumeError;

  const ForceResumeReportDto({
    required this.killed,
    required this.survived,
    required this.stillHeld,
    required this.resumed,
    this.resumeError,
  });

  @override
  int get hashCode =>
      killed.hashCode ^
      survived.hashCode ^
      stillHeld.hashCode ^
      resumed.hashCode ^
      resumeError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ForceResumeReportDto &&
          runtimeType == other.runtimeType &&
          killed == other.killed &&
          survived == other.survived &&
          stillHeld == other.stillHeld &&
          resumed == other.resumed &&
          resumeError == other.resumeError;
}

/// A process holding a session's rollout open (a would-be takeover
/// target), mirrored for Dart.
class HolderDto {
  /// Operating-system process id.
  final PlatformInt64 pid;

  /// Process image name (e.g. `codex.exe`).
  final String name;

  const HolderDto({required this.pid, required this.name});

  @override
  int get hashCode => pid.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HolderDto &&
          runtimeType == other.runtimeType &&
          pid == other.pid &&
          name == other.name;
}

/// A session discovered under `CODEX_HOME`, with the state the UI needs to
/// render it read-only or resumable, mirrored for Dart.
class LocalSessionDto {
  /// Thread / conversation id.
  final String threadId;

  /// Working directory the session controls, when recorded.
  final String? cwd;

  /// Best-effort first-user-message preview.
  final String preview;

  /// Originating client (`cli` / `vscode` / …), when recorded.
  final String? source;

  /// Last-modified time of the rollout, unix seconds.
  final PlatformInt64 updatedAt;

  /// Most-recent-turn state (`empty`/`completed`/`aborted`/`incomplete`).
  final String turnState;

  /// Whether the rollout is currently held open by a live process.
  final bool heldOpen;

  /// Resume-safety tag (`resumable`/`resumableUnfinished`/`ownedRunning`/
  /// `ownedIdle`).
  final String safety;

  /// Whether the UI may offer a resume action (false only while a turn is
  /// actively running).
  final bool allowsResume;

  /// Whether resuming requires a force takeover (a live owner must be
  /// evicted first).
  final bool requiresTakeover;

  const LocalSessionDto({
    required this.threadId,
    this.cwd,
    required this.preview,
    this.source,
    required this.updatedAt,
    required this.turnState,
    required this.heldOpen,
    required this.safety,
    required this.allowsResume,
    required this.requiresTakeover,
  });

  @override
  int get hashCode =>
      threadId.hashCode ^
      cwd.hashCode ^
      preview.hashCode ^
      source.hashCode ^
      updatedAt.hashCode ^
      turnState.hashCode ^
      heldOpen.hashCode ^
      safety.hashCode ^
      allowsResume.hashCode ^
      requiresTakeover.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalSessionDto &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          cwd == other.cwd &&
          preview == other.preview &&
          source == other.source &&
          updatedAt == other.updatedAt &&
          turnState == other.turnState &&
          heldOpen == other.heldOpen &&
          safety == other.safety &&
          allowsResume == other.allowsResume &&
          requiresTakeover == other.requiresTakeover;
}

/// One captured runtime log line for the in-app log viewer.
class LogLineDto {
  /// `TRACE` / `DEBUG` / `INFO` / `WARN` / `ERROR`.
  final String level;

  /// Event target (crate / module path).
  final String target;

  /// The rendered message + any structured fields.
  final String message;

  /// Capture time, unix milliseconds.
  final PlatformInt64 timestampMs;

  const LogLineDto({
    required this.level,
    required this.target,
    required this.message,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      level.hashCode ^
      target.hashCode ^
      message.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogLineDto &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          target == other.target &&
          message == other.message &&
          timestampMs == other.timestampMs;
}

/// One model offered by the app-server, mirrored for Dart.
class ModelInfoDto {
  /// Model id (used as the `model` param).
  final String id;

  /// Human-readable name.
  final String displayName;

  /// Short description.
  final String description;

  /// Reasoning efforts this model supports (so the UI offers only valid
  /// levels).
  final List<String> supportedReasoningEfforts;

  /// The model's default reasoning effort, if any.
  final String? defaultReasoningEffort;

  const ModelInfoDto({
    required this.id,
    required this.displayName,
    required this.description,
    required this.supportedReasoningEfforts,
    this.defaultReasoningEffort,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      description.hashCode ^
      supportedReasoningEfforts.hashCode ^
      defaultReasoningEffort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelInfoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          description == other.description &&
          supportedReasoningEfforts == other.supportedReasoningEfforts &&
          defaultReasoningEffort == other.defaultReasoningEffort;
}

/// The host's project-folder config (mirrored for Dart): the roots a remote
/// folder browser is confined to, and the default project new sessions open in.
class ProjectConfigDto {
  /// Absolute host paths configured as project roots.
  final List<String> projectRoots;

  /// Absolute host path new conversations default to (`None` = codex
  /// default).
  final String? defaultProject;

  const ProjectConfigDto({required this.projectRoots, this.defaultProject});

  @override
  int get hashCode => projectRoots.hashCode ^ defaultProject.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectConfigDto &&
          runtimeType == other.runtimeType &&
          projectRoots == other.projectRoots &&
          defaultProject == other.defaultProject;
}

/// One in-flight retry of a host meta request, mirrored for Dart.
class RetryProgressDto {
  /// Attempts made so far (1-based).
  final int attempt;

  /// Total attempt budget before the request gives up.
  final int maxAttempts;

  const RetryProgressDto({required this.attempt, required this.maxAttempts});

  @override
  int get hashCode => attempt.hashCode ^ maxAttempts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RetryProgressDto &&
          runtimeType == other.runtimeType &&
          attempt == other.attempt &&
          maxAttempts == other.maxAttempts;
}

/// A discovered service, mirrored for Dart.
class ServiceIdDto {
  /// Device id segment.
  final String device;

  /// `app` or `api`.
  final String kind;

  /// Instance name segment.
  final String name;

  /// Full relay key.
  final String key;

  const ServiceIdDto({
    required this.device,
    required this.kind,
    required this.name,
    required this.key,
  });

  @override
  int get hashCode =>
      device.hashCode ^ kind.hashCode ^ name.hashCode ^ key.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServiceIdDto &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          kind == other.kind &&
          name == other.name &&
          key == other.key;
}

/// One full read-only transcript + ownership snapshot from the host's live
/// session follow stream, mirrored for Dart.
class SessionFollowUpdateDto {
  /// Current ownership and resume-safety state.
  final SessionLivenessDto liveness;

  /// Full materialised transcript at this rollout revision.
  final List<ThreadItemDto> items;

  const SessionFollowUpdateDto({required this.liveness, required this.items});

  @override
  int get hashCode => liveness.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionFollowUpdateDto &&
          runtimeType == other.runtimeType &&
          liveness == other.liveness &&
          items == other.items;
}

/// One session's liveness detail, including the would-be takeover targets,
/// mirrored for Dart.
class SessionLivenessDto {
  /// Thread / conversation id.
  final String threadId;

  /// Most-recent-turn state tag.
  final String turnState;

  /// Whether the rollout is currently held open.
  final bool heldOpen;

  /// Resume-safety tag.
  final String safety;

  /// Whether the UI may offer a resume action.
  final bool allowsResume;

  /// Whether resuming requires a force takeover.
  final bool requiresTakeover;

  /// Processes a force takeover would attempt to terminate (Pocket-Codex's
  /// own app-server already excluded).
  final List<HolderDto> holders;

  const SessionLivenessDto({
    required this.threadId,
    required this.turnState,
    required this.heldOpen,
    required this.safety,
    required this.allowsResume,
    required this.requiresTakeover,
    required this.holders,
  });

  @override
  int get hashCode =>
      threadId.hashCode ^
      turnState.hashCode ^
      heldOpen.hashCode ^
      safety.hashCode ^
      allowsResume.hashCode ^
      requiresTakeover.hashCode ^
      holders.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionLivenessDto &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          turnState == other.turnState &&
          heldOpen == other.heldOpen &&
          safety == other.safety &&
          allowsResume == other.allowsResume &&
          requiresTakeover == other.requiresTakeover &&
          holders == other.holders;
}

/// Status of one active subscription, mirrored for Dart.
class SubStatusDto {
  /// Service key.
  final String key;

  /// Local `host:port`.
  final String localAddr;

  /// Task still running.
  final bool alive;

  const SubStatusDto({
    required this.key,
    required this.localAddr,
    required this.alive,
  });

  @override
  int get hashCode => key.hashCode ^ localAddr.hashCode ^ alive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubStatusDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          localAddr == other.localAddr &&
          alive == other.alive;
}

/// Per-thread session config persisted on the host (mirrored for Dart). Every
/// field is optional: `None`/null means "no stored preference", so the UI falls
/// back to its own default.
class ThreadConfigDto {
  /// Selected model id, when pinned for this thread.
  final String? model;

  /// Reasoning-effort tag (`minimal`/`low`/`medium`/`high`), when set.
  final String? reasoningEffort;

  /// Permission / approval mode tag, when set.
  final String? permissionMode;

  /// Whether plan mode is on for this thread, when set.
  final bool? planMode;

  const ThreadConfigDto({
    this.model,
    this.reasoningEffort,
    this.permissionMode,
    this.planMode,
  });

  @override
  int get hashCode =>
      model.hashCode ^
      reasoningEffort.hashCode ^
      permissionMode.hashCode ^
      planMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadConfigDto &&
          runtimeType == other.runtimeType &&
          model == other.model &&
          reasoningEffort == other.reasoningEffort &&
          permissionMode == other.permissionMode &&
          planMode == other.planMode;
}

/// A thread's recovered history + whether a turn is still running, plus the
/// metadata the status bar / git chip seed from on open.
class ThreadHistoryDto {
  /// Conversation items, oldest first.
  final List<ThreadItemDto> items;

  /// Whether the most recent turn is still in progress.
  final bool running;

  /// Current git branch of the thread's cwd, if it's a repo.
  final String? branch;

  /// The thread's resolved working directory (for git diff / status).
  final String? cwd;

  /// Tokens currently occupying the model context window.
  final PlatformInt64? tokensUsed;

  /// The model's context-window size in tokens.
  final PlatformInt64? contextWindow;

  /// Sticky collaboration mode (`"plan"` / `"default"`) so the UI plan toggle
  /// reflects the server's real state.
  final String? collaborationMode;

  /// Current reasoning effort (`"low"`/`"medium"`/`"high"`) so the UI can
  /// show the "thinking level" the thread runs with (from the resume
  /// response).
  final String? reasoningEffort;

  /// The effective model id the thread runs with, per the server. `None`
  /// when the server never reported it (older servers).
  final String? model;

  /// Provider of the effective model (e.g. `openai`), when reported.
  final String? modelProvider;

  /// The effective approval policy (`untrusted`/`on-failure`/`on-request`/
  /// `never`/`granular`), when reported.
  final String? approvalPolicy;

  /// The effective sandbox mode (`read-only`/`workspace-write`/
  /// `danger-full-access`/`external-sandbox`), when reported.
  final String? sandboxMode;

  /// Whether a live `thread/settings/updated` notification has confirmed
  /// this config (vs only a start/resume snapshot).
  final bool configConfirmed;

  const ThreadHistoryDto({
    required this.items,
    required this.running,
    this.branch,
    this.cwd,
    this.tokensUsed,
    this.contextWindow,
    this.collaborationMode,
    this.reasoningEffort,
    this.model,
    this.modelProvider,
    this.approvalPolicy,
    this.sandboxMode,
    required this.configConfirmed,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      running.hashCode ^
      branch.hashCode ^
      cwd.hashCode ^
      tokensUsed.hashCode ^
      contextWindow.hashCode ^
      collaborationMode.hashCode ^
      reasoningEffort.hashCode ^
      model.hashCode ^
      modelProvider.hashCode ^
      approvalPolicy.hashCode ^
      sandboxMode.hashCode ^
      configConfirmed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadHistoryDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          running == other.running &&
          branch == other.branch &&
          cwd == other.cwd &&
          tokensUsed == other.tokensUsed &&
          contextWindow == other.contextWindow &&
          collaborationMode == other.collaborationMode &&
          reasoningEffort == other.reasoningEffort &&
          model == other.model &&
          modelProvider == other.modelProvider &&
          approvalPolicy == other.approvalPolicy &&
          sandboxMode == other.sandboxMode &&
          configConfirmed == other.configConfirmed;
}

/// One materialised conversation item mirrored for Dart.
class ThreadItemDto {
  /// Item id.
  final String id;

  /// Item type tag (`userMessage` / `agentMessage` / `commandExecution` /
  /// `webSearch` / `mcpToolCall` / `fileChange` / `reasoning` / …).
  final String itemType;

  /// One-line summary for tool/activity items.
  final String title;

  /// Body / detail text.
  final String text;

  /// Image URLs attached to a `userMessage`: `data:image/...` URLs render
  /// inline; a host-local path (from a `localImage` input) renders as a
  /// filename chip. Empty for every other item kind.
  final List<String> images;

  /// Id of the turn this item belongs to — the server's own turn boundary
  /// (`thread/read` nests items under their turn), so the UI can render one
  /// turn's reply as one block instead of inferring boundaries from the item
  /// sequence. Empty when the item came from the live stream buffer.
  final String turnId;

  /// Unix seconds when this item's turn completed; `None` while it runs.
  final PlatformInt64? turnCompletedAt;

  /// This item's turn duration in milliseconds, when the server reports it.
  final PlatformInt64? turnDurationMs;

  const ThreadItemDto({
    required this.id,
    required this.itemType,
    required this.title,
    required this.text,
    required this.images,
    required this.turnId,
    this.turnCompletedAt,
    this.turnDurationMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      itemType.hashCode ^
      title.hashCode ^
      text.hashCode ^
      images.hashCode ^
      turnId.hashCode ^
      turnCompletedAt.hashCode ^
      turnDurationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadItemDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          itemType == other.itemType &&
          title == other.title &&
          text == other.text &&
          images == other.images &&
          turnId == other.turnId &&
          turnCompletedAt == other.turnCompletedAt &&
          turnDurationMs == other.turnDurationMs;
}

/// Thread summary mirrored for Dart.
class ThreadMetaDto {
  /// Thread id.
  final String id;

  /// Preview (usually the first user message).
  final String preview;

  /// User-set title, or `None` when the thread was never renamed (the UI
  /// falls back to `preview`).
  final String? name;

  /// Working directory (the project the thread controls).
  final String cwd;

  /// Unix seconds of last update.
  final PlatformInt64 updatedAt;

  const ThreadMetaDto({
    required this.id,
    required this.preview,
    this.name,
    required this.cwd,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      preview.hashCode ^
      name.hashCode ^
      cwd.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadMetaDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          preview == other.preview &&
          name == other.name &&
          cwd == other.cwd &&
          updatedAt == other.updatedAt;
}

/// The server-reported runtime configuration of a thread — what its turns
/// actually run with. Mirrors the engine cache fed by `thread/start` /
/// `thread/resume` responses and live `thread/settings/updated` notifications;
/// every field is `None` when the server hasn't said (never a guess).
class ThreadRuntimeConfigDto {
  /// Effective model id.
  final String? model;

  /// Provider of the effective model.
  final String? modelProvider;

  /// Effective reasoning effort.
  final String? reasoningEffort;

  /// Effective approval policy.
  final String? approvalPolicy;

  /// Effective sandbox mode (kebab wire string).
  final String? sandboxMode;

  /// Effective collaboration mode (`plan`/`default`), when reported.
  final String? collaborationMode;

  /// True once a live settings update confirmed this config.
  final bool confirmedByUpdate;

  const ThreadRuntimeConfigDto({
    this.model,
    this.modelProvider,
    this.reasoningEffort,
    this.approvalPolicy,
    this.sandboxMode,
    this.collaborationMode,
    required this.confirmedByUpdate,
  });

  @override
  int get hashCode =>
      model.hashCode ^
      modelProvider.hashCode ^
      reasoningEffort.hashCode ^
      approvalPolicy.hashCode ^
      sandboxMode.hashCode ^
      collaborationMode.hashCode ^
      confirmedByUpdate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadRuntimeConfigDto &&
          runtimeType == other.runtimeType &&
          model == other.model &&
          modelProvider == other.modelProvider &&
          reasoningEffort == other.reasoningEffort &&
          approvalPolicy == other.approvalPolicy &&
          sandboxMode == other.sandboxMode &&
          collaborationMode == other.collaborationMode &&
          confirmedByUpdate == other.confirmedByUpdate;
}

/// A started web (authorization-code) login, mirrored for Dart. The caller
/// opens [`Self::authorize_url`] in a browser, captures the redirect to its
/// `redirect_uri`, checks the redirect's `state` equals [`Self::state`], then
/// calls [`account_web_login_exchange`] with the redirect's `exchange_code` and
/// [`Self::code_verifier`].
class WebLoginStartDto {
  /// GitHub authorization URL to open in a browser.
  final String authorizeUrl;

  /// CSRF state to match against the redirect's `state`.
  final String state;

  /// PKCE verifier to pass back to [`account_web_login_exchange`].
  final String codeVerifier;

  /// Resolved backend base URL to echo back to
  /// [`account_web_login_exchange`].
  final String backend;

  const WebLoginStartDto({
    required this.authorizeUrl,
    required this.state,
    required this.codeVerifier,
    required this.backend,
  });

  @override
  int get hashCode =>
      authorizeUrl.hashCode ^
      state.hashCode ^
      codeVerifier.hashCode ^
      backend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebLoginStartDto &&
          runtimeType == other.runtimeType &&
          authorizeUrl == other.authorizeUrl &&
          state == other.state &&
          codeVerifier == other.codeVerifier &&
          backend == other.backend;
}
