// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_key`, `current_relay`, `holder_dto`, `meta_holder_dto`, `thread_config_dto`, `thread_config_from_dto`

/// Initialise the engine with the platform app-support dir (from Dart's
/// path_provider). Must be called once after `RustLib.init()`.
Future<void> initBridge({required String supportDir}) =>
    RustLib.instance.api.crateApiBridgeInitBridge(supportDir: supportDir);

/// Current config view (relay/key presence, locale, and account state).
Future<ConfigView> getConfig() =>
    RustLib.instance.api.crateApiBridgeGetConfig();

/// Set the relay `host:port` and persist.
Future<void> setRelay({required String relay}) =>
    RustLib.instance.api.crateApiBridgeSetRelay(relay: relay);

/// Set the 32-byte MSG_HEADER_KEY and persist (validates length).
Future<void> setKey({required String key}) =>
    RustLib.instance.api.crateApiBridgeSetKey(key: key);

/// Set the UI locale (BCP-47, e.g. `en`/`zh`) and persist. An empty string
/// clears it, meaning the app follows the system locale.
Future<void> setLocale({required String locale}) =>
    RustLib.instance.api.crateApiBridgeSetLocale(locale: locale);

/// Import a `pcx1:` share string: decode, persist relay + key, return relay.
Future<String> importConfig({required String text}) =>
    RustLib.instance.api.crateApiBridgeImportConfig(text: text);

/// Export the current relay+key as a `pcx1:` share string.
Future<String> exportConfig() =>
    RustLib.instance.api.crateApiBridgeExportConfig();

/// Discover services: in account mode from the backend (`/v1/services`), in
/// self-host mode from the relay (applying the stored key first).
Future<List<ServiceIdDto>> discoverServices() =>
    RustLib.instance.api.crateApiBridgeDiscoverServices();

/// Subscribe to an API service, exposing it on `127.0.0.1:<local_port>`.
Future<SubStatusDto> apiSubscribe({
  required String serviceKey,
  required int localPort,
}) => RustLib.instance.api.crateApiBridgeApiSubscribe(
  serviceKey: serviceKey,
  localPort: localPort,
);

/// Stop an API-service subscription.
Future<void> apiUnsubscribe({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeApiUnsubscribe(serviceKey: serviceKey);

/// List all active subscriptions.
Future<List<SubStatusDto>> subscriptions() =>
    RustLib.instance.api.crateApiBridgeSubscriptions();

/// Start hosting a local codex app-server **and** Responses API proxy under the
/// signed-in account, publishing both `app:<name>` and `api:<name>`. Re-hosting
/// a name whose codex is still alive just re-registers any dropped tunnels.
/// `proxy` is the upstream proxy both use to reach chatgpt.com (`None` =
/// inherit env). `embedded` runs codex's app-server in-process (the compiled-in
/// `embedded-codex`) instead of spawning an external binary — desktop only; the
/// `binary_override` is ignored when `embedded` is set. Desktop only.
Future<AppServeDto> appServeStart({
  required int port,
  String? binaryOverride,
  String? name,
  String? proxy,
  required bool embedded,
}) => RustLib.instance.api.crateApiBridgeAppServeStart(
  port: port,
  binaryOverride: binaryOverride,
  name: name,
  proxy: proxy,
  embedded: embedded,
);

/// Snapshot of every local host (for the status cards + periodic re-probe).
Future<List<AppServeStatusDto>> appServeStatus() =>
    RustLib.instance.api.crateApiBridgeAppServeStatus();

/// Take one tunnel (`kind` = `"app"`/`"api"`/`"meta"`) of a local host off the
/// relay without stopping the host — a reversible unpublish. The codex / API
/// proxy / meta service keep running; [`app_serve_reregister`] re-publishes it.
Future<void> appServeDeregister({required String name, required String kind}) =>
    RustLib.instance.api.crateApiBridgeAppServeDeregister(
      name: name,
      kind: kind,
    );

/// Re-publish a previously deregistered tunnel (`kind` = `"app"`/`"api"`/
/// `"meta"`) of a still-running local host.
Future<void> appServeReregister({required String name, required String kind}) =>
    RustLib.instance.api.crateApiBridgeAppServeReregister(
      name: name,
      kind: kind,
    );

/// Fully stop one local host by name (both tunnels + watchdog + API proxy, and
/// stops codex).
Future<void> appServeStop({required String name}) =>
    RustLib.instance.api.crateApiBridgeAppServeStop(name: name);

/// Stop every local host (called on app quit so a real quit leaves no orphan
/// codex). A no-op when nothing is hosting.
Future<void> appServeStopAll() =>
    RustLib.instance.api.crateApiBridgeAppServeStopAll();

/// The resolved `codex` binary path (persisted config → `$PATH`), or `None` so
/// the UI can prompt the user to point at one.
Future<String?> codexLocate() =>
    RustLib.instance.api.crateApiBridgeCodexLocate();

/// Connect to an app-server service: subscribe on `127.0.0.1:<local_port>`,
/// open the JSON-RPC websocket and run the `initialize` handshake. Idempotent.
Future<void> appConnect({required String serviceKey, required int localPort}) =>
    RustLib.instance.api.crateApiBridgeAppConnect(
      serviceKey: serviceKey,
      localPort: localPort,
    );

/// Whether a live app-server session exists for `service_key`.
bool appIsConnected({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppIsConnected(serviceKey: serviceKey);

/// Disconnect the app-server session and its pb-mapper subscription.
Future<void> appDisconnect({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppDisconnect(serviceKey: serviceKey);

/// Probe whether an app-server is actually REACHABLE — its backend responds to
/// a handshake — rather than merely registered on the relay. The services list
/// uses this so a registered-but-dead app-server (a live relay registrant
/// forwarding to a codex app-server that has died) shows as unreachable instead
/// of a false "online". Opens a transient tunnel + `initialize` with a timeout,
/// then tears it down; a live session short-circuits to `true`.
Future<bool> appProbe({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppProbe(serviceKey: serviceKey);

/// Probe whether an API proxy is actually REACHABLE — its host answers a
/// minimal HTTP request — rather than merely registered on the relay. The
/// services list uses this so a registered-but-dead API proxy (a live relay
/// registrant forwarding to an api-proxy that has died) shows unreachable
/// instead of a false "online", matching the app-server's [`app_probe`]. Opens
/// a transient tunnel, hits the proxy's local 403 fallback (no upstream model
/// call), then tears it down.
Future<bool> apiProbe({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeApiProbe(serviceKey: serviceKey);

/// Stream live app-server events (turn/item notifications) for `service_key`.
/// The Dart side receives one [`AppEventDto`] per notification until the
/// session is disconnected.
Stream<AppEventDto> appEvents({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppEvents(serviceKey: serviceKey);

/// List threads known to the app-server.
Future<List<ThreadMetaDto>> appThreadList({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppThreadList(serviceKey: serviceKey);

/// List the models the app-server offers.
Future<List<ModelInfoDto>> appModelList({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppModelList(serviceKey: serviceKey);

/// Start a new thread / project. `approval_policy` is one of
/// `untrusted` / `on-failure` / `on-request` / `never`; `sandbox` is one of
/// `read-only` / `workspace-write` / `danger-full-access`. Returns the id.
Future<String> appThreadStart({
  required String serviceKey,
  String? model,
  String? cwd,
  String? approvalPolicy,
  String? sandbox,
}) => RustLib.instance.api.crateApiBridgeAppThreadStart(
  serviceKey: serviceKey,
  model: model,
  cwd: cwd,
  approvalPolicy: approvalPolicy,
  sandbox: sandbox,
);

/// Answer a server approval request. `decision` is the wire value the session
/// layer recognises: `accept` or `acceptForSession` to grant, any other value
/// (e.g. `decline`) to decline.
Future<void> appRespondApproval({
  required String serviceKey,
  required String requestId,
  required String decision,
}) => RustLib.instance.api.crateApiBridgeAppRespondApproval(
  serviceKey: serviceKey,
  requestId: requestId,
  decision: decision,
);

/// Answer an `item/tool/requestUserInput` elicitation (the model asking the
/// user structured questions, NOT a command/file approval). `answers_json` is a
/// JSON object mapping each question id to its chosen answer string(s) (option
/// labels and/or free-text), e.g. `{"theme":["山水抒怀"]}`; an empty object
/// `{}` cancels. The session layer wraps it into the protocol's
/// `ToolRequestUserInputResponse` so the model actually receives the user's
/// selections.
Future<void> appRespondUserInput({
  required String serviceKey,
  required String requestId,
  required String answersJson,
}) => RustLib.instance.api.crateApiBridgeAppRespondUserInput(
  serviceKey: serviceKey,
  requestId: requestId,
  answersJson: answersJson,
);

/// Resume an existing thread (load it into the session) before reading it or
/// sending turns; otherwise the server reports "thread not found".
Future<void> appThreadResume({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeAppThreadResume(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Read a thread's conversation items (oldest first) and whether a turn is
/// still running, so re-opening an in-flight thread restores live state.
Future<ThreadHistoryDto> appThreadRead({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeAppThreadRead(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Read the account rate-limit / quota snapshot as raw JSON (5h + weekly
/// windows). Parsed on the Dart side since the shape is nested and volatile.
Future<String> appRateLimits({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeAppRateLimits(serviceKey: serviceKey);

/// Unified diff of the repo at `cwd` vs its remote default branch. Empty when
/// the cwd isn't a git repo or there are no changes.
Future<String> appGitDiff({required String serviceKey, required String cwd}) =>
    RustLib.instance.api.crateApiBridgeAppGitDiff(
      serviceKey: serviceKey,
      cwd: cwd,
    );

/// Start a manual conversation compaction; the server emits `thread/compacted`
/// when done.
Future<void> appCompact({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeAppCompact(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Send a user message, starting a model turn. `model` / `approval_policy` /
/// `sandbox` are optional per-turn overrides (apply to this and subsequent
/// turns) so model and permission can change mid-conversation.
/// `collaboration_mode` ("plan" / "default", or null to leave unchanged) is
/// sticky on the thread, so pass "default" to leave plan mode.
/// `reasoning_effort` ("low"/"medium"/"high", or null for the model default) is
/// the "thinking level" for this turn. The reply streams via [`app_events`];
/// this returns once the turn is accepted.
Future<void> appTurnStart({
  required String serviceKey,
  required String threadId,
  required String text,
  String? model,
  String? approvalPolicy,
  String? sandbox,
  String? collaborationMode,
  String? reasoningEffort,
}) => RustLib.instance.api.crateApiBridgeAppTurnStart(
  serviceKey: serviceKey,
  threadId: threadId,
  text: text,
  model: model,
  approvalPolicy: approvalPolicy,
  sandbox: sandbox,
  collaborationMode: collaborationMode,
  reasoningEffort: reasoningEffort,
);

/// Interrupt the running turn. `turn_id` (from the latest `turn/started`) is
/// required by the server; pass null only if unknown.
Future<void> appTurnInterrupt({
  required String serviceKey,
  required String threadId,
  String? turnId,
}) => RustLib.instance.api.crateApiBridgeAppTurnInterrupt(
  serviceKey: serviceKey,
  threadId: threadId,
  turnId: turnId,
);

/// List every codex session under the shared `CODEX_HOME`, newest first,
/// each annotated with whether it is safe to resume.
///
/// Works without any app-server connection — it reads the local rollout
/// files and process table directly, so it surfaces sessions created by
/// *other* codex clients (the desktop app, the CLI, the VS Code
/// extension) that share this `CODEX_HOME`. Meaningful only when the UI
/// runs on the same machine as those sessions.
Future<List<LocalSessionDto>> appLocalSessions() =>
    RustLib.instance.api.crateApiBridgeAppLocalSessions();

/// Inspect one session's current resume-safety and the processes a force
/// takeover would evict. Poll this before showing a resume button so the
/// UI reflects live ownership (a session can flip between read-only and
/// resumable as the desktop app loads / releases it).
Future<SessionLivenessDto> appSessionLiveness({required String threadId}) =>
    RustLib.instance.api.crateApiBridgeAppSessionLiveness(threadId: threadId);

/// Read a local session's transcript for READ-ONLY viewing. Parses the
/// on-disk rollout directly (no app-server connection, no resume, no write),
/// so it works even while another codex client still owns the session.
/// Items are in the same shape as [`app_thread_read`], so the read-only
/// viewer reuses the live-conversation rendering. Poll it alongside
/// [`app_session_liveness`] to follow a running session and notice when it
/// goes idle (resume-eligible).
Future<List<ThreadItemDto>> appLocalSessionTranscript({
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeAppLocalSessionTranscript(
  threadId: threadId,
);

/// Force-resume a session into the app-server behind `service_key`.
///
/// Best-effort terminates every live process holding the session's rollout
/// open (never Pocket-Codex's own app-server), then issues `thread/resume`
/// regardless of the eviction outcome. The UI must gate this on explicit
/// user confirmation and must not offer it while a turn is actively
/// running (`SessionLivenessDto::allows_resume == false`). The returned
/// report says exactly which processes were killed / survived and whether
/// the resume took.
Future<ForceResumeReportDto> appForceResume({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeAppForceResume(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Remote analogue of [`app_local_sessions`]: list the sessions of the host
/// behind `service_key` via its meta tunnel (loopback when this app is the
/// host, broker when remote). Lets a phone see a desktop host's sessions —
/// including those owned by another codex client.
Future<List<LocalSessionDto>> metaSessions({required String serviceKey}) =>
    RustLib.instance.api.crateApiBridgeMetaSessions(serviceKey: serviceKey);

/// Remote analogue of [`app_session_liveness`].
Future<SessionLivenessDto> metaSessionLiveness({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeMetaSessionLiveness(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Remote analogue of [`app_local_session_transcript`].
Future<List<ThreadItemDto>> metaSessionTranscript({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeMetaSessionTranscript(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Remote analogue of [`app_force_resume`]: the host evicts the rollout's live
/// holders and resumes it into its colocated app-server over loopback. The UI
/// must gate this on explicit confirmation and not offer it while a turn runs.
Future<ForceResumeReportDto> metaForceResume({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeMetaForceResume(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Read a thread's persisted config from the host behind `service_key`.
Future<ThreadConfigDto> metaThreadConfigGet({
  required String serviceKey,
  required String threadId,
}) => RustLib.instance.api.crateApiBridgeMetaThreadConfigGet(
  serviceKey: serviceKey,
  threadId: threadId,
);

/// Persist a thread's config on the host behind `service_key`; returns the
/// stored value.
Future<ThreadConfigDto> metaThreadConfigSet({
  required String serviceKey,
  required String threadId,
  required ThreadConfigDto config,
}) => RustLib.instance.api.crateApiBridgeMetaThreadConfigSet(
  serviceKey: serviceKey,
  threadId: threadId,
  config: config,
);

/// Begin a GitHub device-flow login. `backend` overrides the configured /
/// default backend (and is remembered on success).
Future<DeviceCodeDto> accountLoginStart({String? backend}) =>
    RustLib.instance.api.crateApiBridgeAccountLoginStart(backend: backend);

/// Poll a device flow once. On `authorized` the session is persisted and the
/// app switches to account mode.
Future<AccountPollDto> accountLoginPoll({
  required String pollHandle,
  required String backend,
}) => RustLib.instance.api.crateApiBridgeAccountLoginPoll(
  pollHandle: pollHandle,
  backend: backend,
);

/// Begin a web (browser-redirect) GitHub login. `redirect_uri` is the
/// platform-specific callback the browser returns to (the app's custom scheme
/// on mobile, a loopback URL on desktop). `backend` overrides the configured /
/// default backend (and is remembered on a successful exchange).
Future<WebLoginStartDto> accountWebLoginStart({
  required String redirectUri,
  String? backend,
}) => RustLib.instance.api.crateApiBridgeAccountWebLoginStart(
  redirectUri: redirectUri,
  backend: backend,
);

/// Redeem the one-time `exchange_code` (with its PKCE `code_verifier`) from the
/// browser redirect. On success the session is persisted and the app switches
/// to account mode. Returns the signed-in identity.
Future<AccountUserDto> accountWebLoginExchange({
  required String exchangeCode,
  required String codeVerifier,
  required String backend,
}) => RustLib.instance.api.crateApiBridgeAccountWebLoginExchange(
  exchangeCode: exchangeCode,
  codeVerifier: codeVerifier,
  backend: backend,
);

/// The signed-in user (verified against the backend), or `None` if not signed
/// in.
Future<AccountUserDto?> accountCurrentUser() =>
    RustLib.instance.api.crateApiBridgeAccountCurrentUser();

/// Sign out: revoke the refresh token (best effort) and clear the local
/// session.
Future<void> accountLogout() =>
    RustLib.instance.api.crateApiBridgeAccountLogout();

/// List the account's services from the backend.
Future<List<AccountServiceDto>> accountServices() =>
    RustLib.instance.api.crateApiBridgeAccountServices();

/// Deregister one of the account's services from the relay (best-effort; a
/// still-running host re-registers shortly after). `kind` is `"app"` or
/// `"api"`.
Future<void> accountDeregisterService({
  required String device,
  required String kind,
  required String name,
}) => RustLib.instance.api.crateApiBridgeAccountDeregisterService(
  device: device,
  kind: kind,
  name: name,
);

/// Outcome of one device-flow poll, mirrored for Dart. `status` is one of
/// `pending` / `slow_down` / `authorized` / `expired` / `denied`; `login` is
/// set only when `authorized`.
class AccountPollDto {
  /// Poll status string.
  final String status;

  /// Signed-in login, when `status == "authorized"`.
  final String? login;

  /// GitHub account id, when authorized and known.
  final String? accountId;

  const AccountPollDto({required this.status, this.login, this.accountId});

  @override
  int get hashCode => status.hashCode ^ login.hashCode ^ accountId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountPollDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          login == other.login &&
          accountId == other.accountId;
}

/// One service in the account, mirrored for Dart (the `pcxu:` prefix stripped).
class AccountServiceDto {
  /// Device id segment.
  final String device;

  /// `app` or `api`.
  final String kind;

  /// Instance name segment.
  final String name;

  const AccountServiceDto({
    required this.device,
    required this.kind,
    required this.name,
  });

  @override
  int get hashCode => device.hashCode ^ kind.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountServiceDto &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          kind == other.kind &&
          name == other.name;
}

/// Signed-in identity mirrored for Dart.
class AccountUserDto {
  /// GitHub login/handle.
  final String login;

  /// GitHub account id, if known.
  final String? accountId;

  const AccountUserDto({required this.login, this.accountId});

  @override
  int get hashCode => login.hashCode ^ accountId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountUserDto &&
          runtimeType == other.runtimeType &&
          login == other.login &&
          accountId == other.accountId;
}

/// One app-server event mirrored for Dart. `kind` is the JSON-RPC method
/// (e.g. `turn/started`, `item/agentMessage/delta`, `turn/completed`).
class AppEventDto {
  /// JSON-RPC method name of the originating notification.
  final String kind;

  /// Thread id the event belongs to, when present.
  final String? threadId;

  /// Item id the event refers to, when present.
  final String? itemId;

  /// Item type tag when this event carries an item (`agentMessage`,
  /// `commandExecution`, `webSearch`, `mcpToolCall`, `fileChange`,
  /// `reasoning`, …); `None` for turn-level events.
  final String? itemType;

  /// One-line summary for tool/activity items (command, query, tool name…).
  final String? title;

  /// Text payload (a streaming delta or an item's body/detail).
  final String? text;

  /// Token to answer a server approval request via [`app_respond_approval`];
  /// `None` for ordinary notifications.
  final String? requestId;

  /// Full params JSON for fields not modelled above.
  final String raw;

  const AppEventDto({
    required this.kind,
    this.threadId,
    this.itemId,
    this.itemType,
    this.title,
    this.text,
    this.requestId,
    required this.raw,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      threadId.hashCode ^
      itemId.hashCode ^
      itemType.hashCode ^
      title.hashCode ^
      text.hashCode ^
      requestId.hashCode ^
      raw.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppEventDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          threadId == other.threadId &&
          itemId == other.itemId &&
          itemType == other.itemType &&
          title == other.title &&
          text == other.text &&
          requestId == other.requestId &&
          raw == other.raw;
}

/// Result of starting local hosting, mirrored for Dart. One host publishes two
/// tunnels (`app:<name>` remote control + `api:<name>` Responses proxy).
class AppServeDto {
  /// Device id both services registered under.
  final String device;

  /// Service instance name (shared by the app + api tunnels).
  final String name;

  /// `pcx:<device>:app:<name>` key (what discovery + `app_connect` use).
  final String appServiceKey;

  /// Loopback `host:port` codex is listening on.
  final String appListenAddr;

  /// `pcx:<device>:api:<name>` key (what an `api connect` resolves).
  final String apiServiceKey;

  /// Loopback `host:port` the in-app Responses API proxy is listening on.
  final String apiListenAddr;

  /// `pcx:<device>:meta:<name>` key (the host meta service tunnel).
  final String metaServiceKey;

  /// Loopback `host:port` the in-app meta service is listening on.
  final String metaListenAddr;

  /// The codex process id.
  final int pid;

  /// Whether an already-running host was reused instead of freshly spawned.
  final bool reused;

  const AppServeDto({
    required this.device,
    required this.name,
    required this.appServiceKey,
    required this.appListenAddr,
    required this.apiServiceKey,
    required this.apiListenAddr,
    required this.metaServiceKey,
    required this.metaListenAddr,
    required this.pid,
    required this.reused,
  });

  @override
  int get hashCode =>
      device.hashCode ^
      name.hashCode ^
      appServiceKey.hashCode ^
      appListenAddr.hashCode ^
      apiServiceKey.hashCode ^
      apiListenAddr.hashCode ^
      metaServiceKey.hashCode ^
      metaListenAddr.hashCode ^
      pid.hashCode ^
      reused.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppServeDto &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          name == other.name &&
          appServiceKey == other.appServiceKey &&
          appListenAddr == other.appListenAddr &&
          apiServiceKey == other.apiServiceKey &&
          apiListenAddr == other.apiListenAddr &&
          metaServiceKey == other.metaServiceKey &&
          metaListenAddr == other.metaListenAddr &&
          pid == other.pid &&
          reused == other.reused;
}

/// Status of one local host, mirrored for Dart. Each host carries both tunnels'
/// publish state so the UI can offer per-tunnel 注销 / 重新注册.
class AppServeStatusDto {
  /// Service instance name.
  final String name;

  /// Device id.
  final String device;

  /// codex process id.
  final int? pid;

  /// codex is accepting on its listen port.
  final bool alive;

  /// Loopback `host:port` codex listens on.
  final String appListenAddr;

  /// `pcx:<device>:app:<name>` key.
  final String appServiceKey;

  /// The app tunnel is currently published.
  final bool appRegistered;

  /// Loopback `host:port` the API proxy listens on.
  final String apiListenAddr;

  /// `pcx:<device>:api:<name>` key.
  final String apiServiceKey;

  /// The api tunnel is currently published.
  final bool apiRegistered;

  /// Loopback `host:port` the meta service listens on.
  final String metaListenAddr;

  /// `pcx:<device>:meta:<name>` key.
  final String metaServiceKey;

  /// The meta tunnel is currently published.
  final bool metaRegistered;

  const AppServeStatusDto({
    required this.name,
    required this.device,
    this.pid,
    required this.alive,
    required this.appListenAddr,
    required this.appServiceKey,
    required this.appRegistered,
    required this.apiListenAddr,
    required this.apiServiceKey,
    required this.apiRegistered,
    required this.metaListenAddr,
    required this.metaServiceKey,
    required this.metaRegistered,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      device.hashCode ^
      pid.hashCode ^
      alive.hashCode ^
      appListenAddr.hashCode ^
      appServiceKey.hashCode ^
      appRegistered.hashCode ^
      apiListenAddr.hashCode ^
      apiServiceKey.hashCode ^
      apiRegistered.hashCode ^
      metaListenAddr.hashCode ^
      metaServiceKey.hashCode ^
      metaRegistered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppServeStatusDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          device == other.device &&
          pid == other.pid &&
          alive == other.alive &&
          appListenAddr == other.appListenAddr &&
          appServiceKey == other.appServiceKey &&
          appRegistered == other.appRegistered &&
          apiListenAddr == other.apiListenAddr &&
          apiServiceKey == other.apiServiceKey &&
          apiRegistered == other.apiRegistered &&
          metaListenAddr == other.metaListenAddr &&
          metaServiceKey == other.metaServiceKey &&
          metaRegistered == other.metaRegistered;
}

/// View of persisted config for the UI; never exposes the raw key or token.
class ConfigView {
  /// Configured relay `host:port`, if any.
  final String? relay;

  /// Whether a 32-byte key is stored (value withheld).
  final bool hasKey;

  /// Configured UI locale (BCP-47, e.g. `en`/`zh`), or `None` to follow
  /// the system locale.
  final String? locale;

  /// Active transport mode: `account` / `self_host` / `unconfigured`.
  final String mode;

  /// Signed-in GitHub login (account mode), if any.
  final String? accountLogin;

  /// Whether an account session token is stored (value withheld).
  final bool hasAccountToken;

  const ConfigView({
    this.relay,
    required this.hasKey,
    this.locale,
    required this.mode,
    this.accountLogin,
    required this.hasAccountToken,
  });

  @override
  int get hashCode =>
      relay.hashCode ^
      hasKey.hashCode ^
      locale.hashCode ^
      mode.hashCode ^
      accountLogin.hashCode ^
      hasAccountToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigView &&
          runtimeType == other.runtimeType &&
          relay == other.relay &&
          hasKey == other.hasKey &&
          locale == other.locale &&
          mode == other.mode &&
          accountLogin == other.accountLogin &&
          hasAccountToken == other.hasAccountToken;
}

/// A started device flow, mirrored for Dart: show the code + URL, then poll.
class DeviceCodeDto {
  /// Code the user types at [`Self::verification_uri`].
  final String userCode;

  /// URL the user opens to enter the code.
  final String verificationUri;

  /// Opaque handle passed back to [`account_login_poll`].
  final String pollHandle;

  /// Minimum seconds between polls.
  final BigInt intervalSecs;

  /// Seconds until the flow expires.
  final BigInt expiresInSecs;

  /// Resolved backend base URL to echo back to [`account_login_poll`].
  final String backend;

  const DeviceCodeDto({
    required this.userCode,
    required this.verificationUri,
    required this.pollHandle,
    required this.intervalSecs,
    required this.expiresInSecs,
    required this.backend,
  });

  @override
  int get hashCode =>
      userCode.hashCode ^
      verificationUri.hashCode ^
      pollHandle.hashCode ^
      intervalSecs.hashCode ^
      expiresInSecs.hashCode ^
      backend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceCodeDto &&
          runtimeType == other.runtimeType &&
          userCode == other.userCode &&
          verificationUri == other.verificationUri &&
          pollHandle == other.pollHandle &&
          intervalSecs == other.intervalSecs &&
          expiresInSecs == other.expiresInSecs &&
          backend == other.backend;
}

/// Outcome of a force-resume, mirrored for Dart.
class ForceResumeReportDto {
  /// Holders that were successfully terminated.
  final List<HolderDto> killed;

  /// Holders the kill could not reach.
  final List<HolderDto> survived;

  /// Whether the rollout is still held open after the attempt (the resume
  /// proceeded regardless).
  final bool stillHeld;

  /// Whether the subsequent `thread/resume` succeeded.
  final bool resumed;

  /// The resume error message, when `resumed` is false.
  final String? resumeError;

  const ForceResumeReportDto({
    required this.killed,
    required this.survived,
    required this.stillHeld,
    required this.resumed,
    this.resumeError,
  });

  @override
  int get hashCode =>
      killed.hashCode ^
      survived.hashCode ^
      stillHeld.hashCode ^
      resumed.hashCode ^
      resumeError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ForceResumeReportDto &&
          runtimeType == other.runtimeType &&
          killed == other.killed &&
          survived == other.survived &&
          stillHeld == other.stillHeld &&
          resumed == other.resumed &&
          resumeError == other.resumeError;
}

/// A process holding a session's rollout open (a would-be takeover
/// target), mirrored for Dart.
class HolderDto {
  /// Operating-system process id.
  final PlatformInt64 pid;

  /// Process image name (e.g. `codex.exe`).
  final String name;

  const HolderDto({required this.pid, required this.name});

  @override
  int get hashCode => pid.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HolderDto &&
          runtimeType == other.runtimeType &&
          pid == other.pid &&
          name == other.name;
}

/// A session discovered under `CODEX_HOME`, with the state the UI needs to
/// render it read-only or resumable, mirrored for Dart.
class LocalSessionDto {
  /// Thread / conversation id.
  final String threadId;

  /// Working directory the session controls, when recorded.
  final String? cwd;

  /// Best-effort first-user-message preview.
  final String preview;

  /// Originating client (`cli` / `vscode` / …), when recorded.
  final String? source;

  /// Last-modified time of the rollout, unix seconds.
  final PlatformInt64 updatedAt;

  /// Most-recent-turn state (`empty`/`completed`/`aborted`/`incomplete`).
  final String turnState;

  /// Whether the rollout is currently held open by a live process.
  final bool heldOpen;

  /// Resume-safety tag (`resumable`/`resumableUnfinished`/`ownedRunning`/
  /// `ownedIdle`).
  final String safety;

  /// Whether the UI may offer a resume action (false only while a turn is
  /// actively running).
  final bool allowsResume;

  /// Whether resuming requires a force takeover (a live owner must be
  /// evicted first).
  final bool requiresTakeover;

  const LocalSessionDto({
    required this.threadId,
    this.cwd,
    required this.preview,
    this.source,
    required this.updatedAt,
    required this.turnState,
    required this.heldOpen,
    required this.safety,
    required this.allowsResume,
    required this.requiresTakeover,
  });

  @override
  int get hashCode =>
      threadId.hashCode ^
      cwd.hashCode ^
      preview.hashCode ^
      source.hashCode ^
      updatedAt.hashCode ^
      turnState.hashCode ^
      heldOpen.hashCode ^
      safety.hashCode ^
      allowsResume.hashCode ^
      requiresTakeover.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalSessionDto &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          cwd == other.cwd &&
          preview == other.preview &&
          source == other.source &&
          updatedAt == other.updatedAt &&
          turnState == other.turnState &&
          heldOpen == other.heldOpen &&
          safety == other.safety &&
          allowsResume == other.allowsResume &&
          requiresTakeover == other.requiresTakeover;
}

/// One model offered by the app-server, mirrored for Dart.
class ModelInfoDto {
  /// Model id (used as the `model` param).
  final String id;

  /// Human-readable name.
  final String displayName;

  /// Short description.
  final String description;

  /// Reasoning efforts this model supports (so the UI offers only valid
  /// levels).
  final List<String> supportedReasoningEfforts;

  /// The model's default reasoning effort, if any.
  final String? defaultReasoningEffort;

  const ModelInfoDto({
    required this.id,
    required this.displayName,
    required this.description,
    required this.supportedReasoningEfforts,
    this.defaultReasoningEffort,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      description.hashCode ^
      supportedReasoningEfforts.hashCode ^
      defaultReasoningEffort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelInfoDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          description == other.description &&
          supportedReasoningEfforts == other.supportedReasoningEfforts &&
          defaultReasoningEffort == other.defaultReasoningEffort;
}

/// A discovered service, mirrored for Dart.
class ServiceIdDto {
  /// Device id segment.
  final String device;

  /// `app` or `api`.
  final String kind;

  /// Instance name segment.
  final String name;

  /// Full relay key.
  final String key;

  const ServiceIdDto({
    required this.device,
    required this.kind,
    required this.name,
    required this.key,
  });

  @override
  int get hashCode =>
      device.hashCode ^ kind.hashCode ^ name.hashCode ^ key.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServiceIdDto &&
          runtimeType == other.runtimeType &&
          device == other.device &&
          kind == other.kind &&
          name == other.name &&
          key == other.key;
}

/// One session's liveness detail, including the would-be takeover targets,
/// mirrored for Dart.
class SessionLivenessDto {
  /// Thread / conversation id.
  final String threadId;

  /// Most-recent-turn state tag.
  final String turnState;

  /// Whether the rollout is currently held open.
  final bool heldOpen;

  /// Resume-safety tag.
  final String safety;

  /// Whether the UI may offer a resume action.
  final bool allowsResume;

  /// Whether resuming requires a force takeover.
  final bool requiresTakeover;

  /// Processes a force takeover would attempt to terminate (Pocket-Codex's
  /// own app-server already excluded).
  final List<HolderDto> holders;

  const SessionLivenessDto({
    required this.threadId,
    required this.turnState,
    required this.heldOpen,
    required this.safety,
    required this.allowsResume,
    required this.requiresTakeover,
    required this.holders,
  });

  @override
  int get hashCode =>
      threadId.hashCode ^
      turnState.hashCode ^
      heldOpen.hashCode ^
      safety.hashCode ^
      allowsResume.hashCode ^
      requiresTakeover.hashCode ^
      holders.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionLivenessDto &&
          runtimeType == other.runtimeType &&
          threadId == other.threadId &&
          turnState == other.turnState &&
          heldOpen == other.heldOpen &&
          safety == other.safety &&
          allowsResume == other.allowsResume &&
          requiresTakeover == other.requiresTakeover &&
          holders == other.holders;
}

/// Status of one active subscription, mirrored for Dart.
class SubStatusDto {
  /// Service key.
  final String key;

  /// Local `host:port`.
  final String localAddr;

  /// Task still running.
  final bool alive;

  const SubStatusDto({
    required this.key,
    required this.localAddr,
    required this.alive,
  });

  @override
  int get hashCode => key.hashCode ^ localAddr.hashCode ^ alive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubStatusDto &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          localAddr == other.localAddr &&
          alive == other.alive;
}

/// Per-thread session config persisted on the host (mirrored for Dart). Every
/// field is optional: `None`/null means "no stored preference", so the UI falls
/// back to its own default.
class ThreadConfigDto {
  /// Selected model id, when pinned for this thread.
  final String? model;

  /// Reasoning-effort tag (`minimal`/`low`/`medium`/`high`), when set.
  final String? reasoningEffort;

  /// Permission / approval mode tag, when set.
  final String? permissionMode;

  /// Whether plan mode is on for this thread, when set.
  final bool? planMode;

  const ThreadConfigDto({
    this.model,
    this.reasoningEffort,
    this.permissionMode,
    this.planMode,
  });

  @override
  int get hashCode =>
      model.hashCode ^
      reasoningEffort.hashCode ^
      permissionMode.hashCode ^
      planMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadConfigDto &&
          runtimeType == other.runtimeType &&
          model == other.model &&
          reasoningEffort == other.reasoningEffort &&
          permissionMode == other.permissionMode &&
          planMode == other.planMode;
}

/// A thread's recovered history + whether a turn is still running, plus the
/// metadata the status bar / git chip seed from on open.
class ThreadHistoryDto {
  /// Conversation items, oldest first.
  final List<ThreadItemDto> items;

  /// Whether the most recent turn is still in progress.
  final bool running;

  /// Current git branch of the thread's cwd, if it's a repo.
  final String? branch;

  /// The thread's resolved working directory (for git diff / status).
  final String? cwd;

  /// Tokens currently occupying the model context window.
  final PlatformInt64? tokensUsed;

  /// The model's context-window size in tokens.
  final PlatformInt64? contextWindow;

  /// Sticky collaboration mode (`"plan"` / `"default"`) so the UI plan toggle
  /// reflects the server's real state.
  final String? collaborationMode;

  /// Current reasoning effort (`"low"`/`"medium"`/`"high"`) so the UI can
  /// show the "thinking level" the thread runs with (from the resume
  /// response).
  final String? reasoningEffort;

  const ThreadHistoryDto({
    required this.items,
    required this.running,
    this.branch,
    this.cwd,
    this.tokensUsed,
    this.contextWindow,
    this.collaborationMode,
    this.reasoningEffort,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      running.hashCode ^
      branch.hashCode ^
      cwd.hashCode ^
      tokensUsed.hashCode ^
      contextWindow.hashCode ^
      collaborationMode.hashCode ^
      reasoningEffort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadHistoryDto &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          running == other.running &&
          branch == other.branch &&
          cwd == other.cwd &&
          tokensUsed == other.tokensUsed &&
          contextWindow == other.contextWindow &&
          collaborationMode == other.collaborationMode &&
          reasoningEffort == other.reasoningEffort;
}

/// One materialised conversation item mirrored for Dart.
class ThreadItemDto {
  /// Item id.
  final String id;

  /// Item type tag (`userMessage` / `agentMessage` / `commandExecution` /
  /// `webSearch` / `mcpToolCall` / `fileChange` / `reasoning` / …).
  final String itemType;

  /// One-line summary for tool/activity items.
  final String title;

  /// Body / detail text.
  final String text;

  const ThreadItemDto({
    required this.id,
    required this.itemType,
    required this.title,
    required this.text,
  });

  @override
  int get hashCode =>
      id.hashCode ^ itemType.hashCode ^ title.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadItemDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          itemType == other.itemType &&
          title == other.title &&
          text == other.text;
}

/// Thread summary mirrored for Dart.
class ThreadMetaDto {
  /// Thread id.
  final String id;

  /// Preview (usually the first user message).
  final String preview;

  /// Working directory (the project the thread controls).
  final String cwd;

  /// Unix seconds of last update.
  final PlatformInt64 updatedAt;

  const ThreadMetaDto({
    required this.id,
    required this.preview,
    required this.cwd,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ preview.hashCode ^ cwd.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThreadMetaDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          preview == other.preview &&
          cwd == other.cwd &&
          updatedAt == other.updatedAt;
}

/// A started web (authorization-code) login, mirrored for Dart. The caller
/// opens [`Self::authorize_url`] in a browser, captures the redirect to its
/// `redirect_uri`, checks the redirect's `state` equals [`Self::state`], then
/// calls [`account_web_login_exchange`] with the redirect's `exchange_code` and
/// [`Self::code_verifier`].
class WebLoginStartDto {
  /// GitHub authorization URL to open in a browser.
  final String authorizeUrl;

  /// CSRF state to match against the redirect's `state`.
  final String state;

  /// PKCE verifier to pass back to [`account_web_login_exchange`].
  final String codeVerifier;

  /// Resolved backend base URL to echo back to
  /// [`account_web_login_exchange`].
  final String backend;

  const WebLoginStartDto({
    required this.authorizeUrl,
    required this.state,
    required this.codeVerifier,
    required this.backend,
  });

  @override
  int get hashCode =>
      authorizeUrl.hashCode ^
      state.hashCode ^
      codeVerifier.hashCode ^
      backend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebLoginStartDto &&
          runtimeType == other.runtimeType &&
          authorizeUrl == other.authorizeUrl &&
          state == other.state &&
          codeVerifier == other.codeVerifier &&
          backend == other.backend;
}
