// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Greet a Pocket-Codex user.
///
/// `flutter_rust_bridge` exposes this synchronously to Dart so the
/// front-end can call it without needing `await`.
String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Return the bridge crate's package version. Useful as a "ping" the
/// UI can show to confirm the native library loaded.
String bridgeVersion() => RustLib.instance.api.crateApiSimpleBridgeVersion();
