//! The embedded agent catalog (TRD §4.3.1, D12): pinned versions with
//! integrity hashes, generated by `scripts/acp_catalog.py`.

use std::{collections::BTreeMap, sync::OnceLock};

use serde::Deserialize;

use super::super::error::AcpError;

/// The embedded catalog text.
const EMBEDDED: &str = include_str!("catalog/catalog.toml");

/// The agent catalog.
#[derive(Clone, Debug, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct Catalog {
    /// Format version (1).
    pub schema: u32,
    /// When the catalog was generated.
    pub generated_at: String,
    /// Private Node runtime; `None` only in the placeholder catalog.
    pub node: Option<NodePin>,
    /// Installable agents.
    pub agents: Vec<CatalogAgent>,
}

/// Pinned Node runtime.
#[derive(Clone, Debug, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct NodePin {
    /// Version without the leading `v`.
    pub version: String,
    /// Platform key → archive.
    pub targets: BTreeMap<String, ArchiveTarget>,
}

/// One downloadable archive.
#[derive(Clone, Debug, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct ArchiveTarget {
    /// HTTPS URL.
    pub url: String,
    /// SRI string (`sha256-…` / `sha512-…`).
    pub integrity: String,
    /// Top-level directory inside the archive.
    pub root: Option<String>,
    /// Executable relative to the extraction directory.
    pub cmd: Option<String>,
}

/// One installable agent.
#[derive(Clone, Debug, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct CatalogAgent {
    /// Catalog id.
    pub id: String,
    /// Display name.
    pub name: String,
    /// Description.
    pub description: String,
    /// Id in the ACP registry, for new-version hints.
    pub registry_id: Option<String>,
    /// Approximate installed size.
    pub approx_size_mb: u32,
    /// Optional engine executable override (Claude, D7).
    pub engine_override: Option<EngineOverride>,
    /// Required external engine (codex-acp, D6).
    pub external_engine: Option<ExternalEngine>,
    /// Newest first.
    pub releases: Vec<Release>,
}

impl CatalogAgent {
    /// Whether installing needs the private Node runtime.
    pub fn needs_node(&self) -> bool {
        self.releases
            .iter()
            .any(|r| matches!(r.kind, ReleaseKind::Npm { .. }))
    }

    /// Release with `version`.
    pub fn release(&self, version: &str) -> Option<&Release> {
        self.releases.iter().find(|r| r.version == version)
    }
}

/// One pinned release.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize)]
pub struct Release {
    /// Version.
    pub version: String,
    /// Supported external engine versions (semver requirement).
    #[serde(default)]
    pub engine_range: Option<String>,
    /// How it is installed.
    #[serde(flatten)]
    pub kind: ReleaseKind,
    /// Extra arguments.
    #[serde(default)]
    pub args: Vec<String>,
    /// Fixed environment.
    #[serde(default)]
    pub env: BTreeMap<String, String>,
    /// Variables set to a fresh random value on every start.
    #[serde(default)]
    pub random_env: Vec<String>,
    /// OpenCode data family (D19).
    #[serde(default)]
    pub data_family: Option<String>,
    /// Settings-driven launch-only arguments (D21).
    #[serde(default)]
    pub conditional_args: Vec<ConditionalArgs>,
}

/// Boolean setting read from `[agents.<id>]` in agents.toml. `label_key` /
/// `confirm_key` are l10n keys the UI uses to render a switch (and a confirm
/// dialog when turning it on).
#[derive(Clone, Debug, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct ConditionalArgs {
    /// Setting name.
    pub setting: String,
    /// Value when unset.
    pub default: bool,
    /// Arguments when true.
    pub when_true: Vec<String>,
    /// Arguments when false.
    pub when_false: Vec<String>,
    /// UI label key.
    pub label_key: String,
    /// UI confirm key when turning it on.
    pub confirm_key: Option<String>,
}

/// Install method of a release.
#[derive(Clone, Debug, PartialEq, Eq, Deserialize)]
#[serde(tag = "kind", rename_all = "lowercase")]
pub enum ReleaseKind {
    /// npm package installed with the private Node and a pinned lockfile.
    Npm {
        /// Package name.
        package: String,
        /// Entry script relative to the prefix.
        entry: String,
        /// Lockfile name in `catalog/locks/`.
        lock: String,
        /// `npm ci --omit=<x>` values.
        #[serde(default)]
        omit: Vec<String>,
        /// Supported platform keys.
        #[serde(default)]
        platforms: Vec<String>,
    },
    /// Prebuilt archive per platform.
    Archive {
        /// Platform key (optionally `-baseline`) → archive.
        #[serde(default)]
        targets: BTreeMap<String, ArchiveTarget>,
    },
}

/// External engine the adapter drives (codex-acp → the user's codex).
#[derive(Clone, Debug, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct ExternalEngine {
    /// Environment variable carrying the engine path.
    pub env: String,
    /// Executable name.
    pub binary: String,
    /// `[agents.<id>]` key overriding the path.
    pub setting: String,
    /// Arguments printing the version.
    pub version_args: Vec<String>,
}

/// Optional engine override (Claude Code executable).
#[derive(Clone, Debug, Default, PartialEq, Eq, Deserialize)]
#[serde(default)]
pub struct EngineOverride {
    /// Environment variable.
    pub env: String,
    /// `[agents.<id>]` key.
    pub setting: String,
}

/// Parse any catalog text; installer tests use their own small catalogs.
pub fn parse_catalog(text: &str) -> Result<Catalog, AcpError> {
    let catalog: Catalog =
        toml::from_str(text).map_err(|e| AcpError::Internal(format!("invalid catalog: {e}")))?;
    if catalog.schema != 1 {
        return Err(AcpError::Internal(format!("unsupported catalog schema {}", catalog.schema)));
    }
    Ok(catalog)
}

/// The embedded catalog, parsed once; `embedded_catalog_parses` guards it.
pub fn catalog() -> &'static Catalog {
    static CATALOG: OnceLock<Catalog> = OnceLock::new();
    CATALOG.get_or_init(|| parse_catalog(EMBEDDED).unwrap_or_default())
}

/// The embedded catalog text (for the parse test).
pub fn embedded_text() -> &'static str {
    EMBEDDED
}
